from __future__ import annotations

from typing import Any, Dict, Iterable, List

from .validation import validation_summary

SOURCE_CONFIDENCE_LABELS: Dict[str, Dict[str, str]] = {'local_source': {'key': 'local_source',
                  'label': 'Local source',
                  'description': 'Anchored in the local Chinese Astrology corpus notes.'},
 'computed_rule': {'key': 'computed_rule',
                   'label': 'Computed rule',
                   'description': 'Produced by deterministic tables or calendrical calculation.'},
 'school_variant': {'key': 'school_variant',
                    'label': 'School variant',
                    'description': 'Known to vary across BaZi schools or practitioner lineages.'},
 'provisional_model': {'key': 'provisional_model',
                       'label': 'Provisional model',
                       'description': 'Implemented with source gates and still awaiting wider fixture calibration.'},
 'needs_validation': {'key': 'needs_validation',
                      'label': 'Needs validation',
                      'description': 'Requires curated examples before being treated as production-calibrated.'}}

RULE_NOTES: List[Dict[str, Any]] = [{'id': 'pillars.year_li_chun',
  'label': 'Year Pillar Boundary',
  'area': 'pillars',
  'status': 'implemented_needs_fixture_expansion',
  'source_ids': ['local.four_pillars_strength'],
  'source_confidence': [{'key': 'local_source',
                         'label': 'Local source',
                         'description': 'Anchored in the local Chinese Astrology corpus notes.'},
                        {'key': 'computed_rule',
                         'label': 'Computed rule',
                         'description': 'Produced by deterministic tables or calendrical calculation.'},
                        {'key': 'school_variant',
                         'label': 'School variant',
                         'description': 'Known to vary across BaZi schools or practitioner lineages.'}],
  'implementation': 'The BaZi Year Pillar preset changes at astronomical Li Chun. This is a Four Pillars convention, not the official Chinese-calendar year rollover at Lunar New Year; Four Pillars are read as Tian Gan/Di Zhi columns ordered Hour, Day, Month, Year.',
  'curation_needed': 'Add historical BaZi almanac examples around Li Chun for several time zones and keep the BaZi convention visibly distinct from the official Chinese-calendar year.'},
 {'id': 'pillars.month_jie_terms',
  'label': 'Month Pillar Solar Terms',
  'area': 'solar_terms',
  'status': 'implemented_needs_fixture_expansion',
  'source_ids': ['local.four_pillars_strength'],
  'source_confidence': [{'key': 'local_source',
                         'label': 'Local source',
                         'description': 'Anchored in the local Chinese Astrology corpus notes.'},
                        {'key': 'computed_rule',
                         'label': 'Computed rule',
                         'description': 'Produced by deterministic tables or calendrical calculation.'}],
  'implementation': 'Month pillar follows the twelve Jie term boundaries and carries the primary seasonal authority for Day Master strength.',
  'curation_needed': 'Add exact boundary examples for each Jie term and verify Swiss Ephemeris fallback behavior.'},
 {'id': 'pillars.hour_civil_true_solar',
  'label': 'Hour Pillar Civil vs True Solar',
  'area': 'true_solar_time',
  'status': 'implemented_variant_guarded',
  'source_ids': ['web.noaa_true_solar_time', 'web.usno_equation_of_time'],
  'source_confidence': [{'key': 'computed_rule',
                         'label': 'Computed rule',
                         'description': 'Produced by deterministic tables or calendrical calculation.'},
                        {'key': 'school_variant',
                         'label': 'School variant',
                         'description': 'Known to vary across BaZi schools or practitioner lineages.'},
                        {'key': 'needs_validation',
                         'label': 'Needs validation',
                         'description': 'Requires curated examples before being treated as production-calibrated.'}],
  'implementation': 'Civil local hour is default; true solar can optionally replace the hour pillar, and true-solar '
                    'day boundary can be selected as a school variant.',
  'curation_needed': 'Curate school guidance and historical examples for day-boundary handling when true solar crosses '
                     'the civil date.'},
 {'id': 'pillars.late_zi_day_boundary',
  'label': 'Late Zi-Hour Day Variant',
  'area': 'pillars',
  'status': 'implemented_variant_guarded',
  'source_ids': ['local.four_pillars_strength'],
  'source_confidence': [{'key': 'local_source',
                         'label': 'Local source',
                         'description': 'Anchored in the local Chinese Astrology corpus notes.'},
                        {'key': 'computed_rule',
                         'label': 'Computed rule',
                         'description': 'Produced by deterministic tables or calendrical calculation.'},
                        {'key': 'school_variant',
                         'label': 'School variant',
                         'description': 'Known to vary across BaZi schools or practitioner lineages.'}],
  'implementation': 'Default keeps civil day at 23:00; optional late-Zi variant advances the Day Pillar from 23:00 to '
                    '23:59.',
  'curation_needed': 'Add source examples showing standard Zi hour versus late-Zi next-day practice.'},
 {'id': 'ten_gods.five_factor_profile',
  'label': 'Ten Gods / Five Factors',
  'area': 'ten_gods',
  'status': 'implemented_source_preview',
  'source_ids': ['local.destiny_code_five_factors', 'local.four_pillars_strength'],
  'source_confidence': [{'key': 'local_source',
                         'label': 'Local source',
                         'description': 'Anchored in the local Chinese Astrology corpus notes.'},
                        {'key': 'computed_rule',
                         'label': 'Computed rule',
                         'description': 'Produced by deterministic tables or calendrical calculation.'}],
  'implementation': 'Visible Tian Gan and branch hidden stems are mapped from the Day Master through Five Factor families before direct/indirect Ten Gods are expanded.',
  'curation_needed': 'Add topic examples for direct and indirect Ten God pairs.'},
 {'id': 'strength.season_root_formation',
  'label': 'Day Master Strength',
  'area': 'strength',
  'status': 'implemented_provisional',
  'source_ids': ['local.four_pillars_strength'],
  'source_confidence': [{'key': 'local_source',
                         'label': 'Local source',
                         'description': 'Anchored in the local Chinese Astrology corpus notes.'},
                        {'key': 'provisional_model',
                         'label': 'Provisional model',
                         'description': 'Implemented with source gates and still awaiting wider fixture calibration.'},
                        {'key': 'needs_validation',
                         'label': 'Needs validation',
                         'description': 'Requires curated examples before being treated as production-calibrated.'}],
  'implementation': 'Strength uses month season first, then Day-branch normal root, Hour-branch secret root, and formation support across the eight palaces and hidden stems.',
  'curation_needed': 'Add source-verified strong, weak, balanced, follow-structure, and special-structure examples.'},
 {'id': 'useful_elements.preview',
  'label': 'Useful/Favorable Element Preview',
  'area': 'useful_elements',
  'status': 'implemented_provisional',
  'source_ids': ['local.destiny_code_favorable_elements'],
  'source_confidence': [{'key': 'local_source',
                         'label': 'Local source',
                         'description': 'Anchored in the local Chinese Astrology corpus notes.'},
                        {'key': 'provisional_model',
                         'label': 'Provisional model',
                         'description': 'Implemented with source gates and still awaiting wider fixture calibration.'},
                        {'key': 'needs_validation',
                         'label': 'Needs validation',
                         'description': 'Requires curated examples before being treated as production-calibrated.'}],
  'implementation': 'Favorable elements are suggested only when strength is strong or weak enough to justify a '
                    'preview; climate/regulating and damaged-useful checks are now shown as separate provisional '
                    'layers.',
  'curation_needed': 'Curate climate/regulating useful-god examples, damaged-useful-element cases, and '
                     'special-structure exceptions.'},
 {'id': 'useful_elements.yong_shen_rule_families',
  'label': 'Yong Shen Decision Families',
  'area': 'useful_elements',
  'status': 'implemented_decision_scaffold',
  'source_ids': ['local.destiny_code_favorable_elements', 'local.destiny_code_damaged_useful_element'],
  'source_confidence': [{'key': 'local_source',
                         'label': 'Local source',
                         'description': 'Anchored in the local Chinese Astrology corpus notes.'},
                        {'key': 'provisional_model',
                         'label': 'Provisional model',
                         'description': 'Implemented with source gates and still awaiting wider fixture calibration.'},
                        {'key': 'needs_validation',
                         'label': 'Needs validation',
                         'description': 'Requires curated examples before being treated as production-calibrated.'}],
  'implementation': 'Yong Shen decisions now expose rule-family paths and blockers for strong balancing, weak support, '
                    'climate override, damaged candidates, special-structure withholding, and balanced withholding.',
  'curation_needed': 'Add positive and negative fixtures for each rule family before any family can return a final '
                     'Yong Shen.'},
 {'id': 'relationships.codes',
  'label': 'Stem/Branch Relationship Codes',
  'area': 'relationships',
  'status': 'implemented_fixture_matrix_seeded',
  'source_ids': ['local.destiny_code_revealed_relationships'],
  'source_confidence': [{'key': 'local_source',
                         'label': 'Local source',
                         'description': 'Anchored in the local Chinese Astrology corpus notes.'},
                        {'key': 'computed_rule',
                         'label': 'Computed rule',
                         'description': 'Produced by deterministic tables or calendrical calculation.'}],
  'implementation': 'Combinations, clashes, harms, destructions, punishments, branch crosses, and complete sets are '
                    'emitted as structured events.',
  'curation_needed': 'Expand beyond one event-type fixture each with page-anchored examples and expected palace/tone '
                     'output.'},
 {'id': 'relationships.spouse_palace',
  'label': 'Day Pillar / Spouse Palace',
  'area': 'compatibility',
  'status': 'implemented_source_preview',
  'source_ids': ['local.four_pillars_palace_context', 'local.destiny_code_revealed_relationships'],
  'source_confidence': [{'key': 'local_source',
                         'label': 'Local source',
                         'description': 'Anchored in the local Chinese Astrology corpus notes.'},
                        {'key': 'computed_rule',
                         'label': 'Computed rule',
                         'description': 'Produced by deterministic tables or calendrical calculation.'}],
  'implementation': 'Pair analysis weights contacts to the Day pillar / partner palace above generic cross-chart '
                    'contacts.',
  'curation_needed': 'Calibrate spouse-palace support/friction examples before treating scores as final.'},
 {'id': 'luck_pillars.direction_start_age',
  'label': 'Luck Pillar Direction And Start Age',
  'area': 'timing',
  'status': 'implemented_variant_guarded',
  'source_ids': ['local.four_pillars_strength'],
  'source_confidence': [{'key': 'local_source',
                         'label': 'Local source',
                         'description': 'Anchored in the local Chinese Astrology corpus notes.'},
                        {'key': 'computed_rule',
                         'label': 'Computed rule',
                         'description': 'Produced by deterministic tables or calendrical calculation.'},
                        {'key': 'school_variant',
                         'label': 'School variant',
                         'description': 'Known to vary across BaZi schools or practitioner lineages.'}],
 'implementation': 'Direction defaults to year-stem polarity, with year-branch and Day Master polarity variants '
                   'exposed; start age uses adjacent Jie distance.',
  'curation_needed': 'Add source examples for every supported direction variant and confirm which should be the '
                     'product default.'},
 {'id': 'timing.rhythm_layers',
  'label': 'BaZi Timing Rhythm',
  'area': 'timing',
  'status': 'implemented_source_preview',
  'source_ids': ['local.four_pillars_strength',
                 'local.destiny_code_five_factors',
                 'local.destiny_code_revealed_relationships',
                 'local.destiny_code_damaged_useful_element'],
  'source_confidence': [{'key': 'local_source',
                         'label': 'Local source',
                         'description': 'Anchored in the local Chinese Astrology corpus notes.'},
                        {'key': 'computed_rule',
                         'label': 'Computed rule',
                         'description': 'Produced by deterministic tables or calendrical calculation.'},
                        {'key': 'provisional_model',
                         'label': 'Provisional model',
                         'description': 'Implemented with source gates and still awaiting wider fixture calibration.'},
                        {'key': 'school_variant',
                         'label': 'School variant',
                         'description': 'Known to vary across BaZi schools or practitioner lineages.'}],
  'implementation': 'Da Yun, annual, flowing month, flowing day, and flowing hour are normalized into one timing '
                    'rhythm layer with Ten God, useful-element, relationship-code, and 12-growth-stage evidence.',
  'curation_needed': 'Expand source examples for monthly/day/hour flowing-pillar interpretation and the 12 growth '
                     'stage table before using rhythm evidence as final outcome scoring.'},
 {'id': 'auxiliary.shen_sha_markers',
  'label': 'Auxiliary Shen Sha Markers',
  'area': 'auxiliary_stars',
  'status': 'implemented_source_anchored',
  'source_ids': ['local.destiny_code_peach_blossom',
                 'local.destiny_code_revealed_peach_blossom',
                 'web.bazitalk_shen_sha_formula_table',
                 'web.fatemaster_yi_ma'],
  'source_confidence': [{'key': 'local_source',
                         'label': 'Local source',
                         'description': 'Anchored in the local Chinese Astrology corpus notes.'},
                        {'key': 'computed_rule',
                         'label': 'Computed rule',
                         'description': 'Produced by deterministic tables or calendrical calculation.'},
                        {'key': 'school_variant',
                         'label': 'School variant',
                         'description': 'Known to vary across BaZi schools or practitioner lineages.'}],
 'implementation': 'Peach Blossom, Traveling Horse, General Star, Wen Chang, Tian Yi, Tian De, and Yue De are detected as formula-based placement markers with natal/timing activation and branch-pressure checks.',
 'curation_needed': 'Add worked examples for each Shen Sha marker family before using markers for scoring or outcome claims.'},
 {'id': 'life_areas.topic_map',
  'label': 'Life Areas Topic Map',
  'area': 'life_areas',
  'status': 'implemented_source_gated',
  'source_ids': ['local.four_pillars_palace_context',
                 'local.destiny_code_five_factors',
                 'local.destiny_code_revealed_four_aspects'],
  'source_confidence': [{'key': 'local_source',
                         'label': 'Local source',
                         'description': 'Anchored in the local Chinese Astrology corpus notes.'},
                        {'key': 'computed_rule',
                         'label': 'Computed rule',
                         'description': 'Produced by deterministic tables or calendrical calculation.'},
                        {'key': 'school_variant',
                         'label': 'School variant',
                         'description': 'Known to vary across BaZi schools or practitioner lineages.'}],
  'implementation': 'Life-area cards combine Five Factor topic roles, four-pillar palace placement, relationship contacts, symbolic element balance, and timing activation without assigning fixed outcomes.',
  'curation_needed': 'Add worked examples for career, wealth, relationships, family, learning, peers, output, and symbolic body-balance topics.'}]

SOURCE_ANCHORS: List[Dict[str, Any]] = [{'id': 'anchor.pillars.li_chun_jie_terms',
  'area': 'solar_terms',
  'source_id': 'local.four_pillars_strength',
  'path': 'output/iching_private_corpus/ba-zi-the-four-pillars-of-destiny.md',
  'anchor_type': 'keyword_anchor',
  'keywords': ['Li Chun',
               'solar term',
               'month pillar',
               'season',
               'Tian Gan',
               'Di Zhi',
               'Hour pillar',
               'Day pillar',
               'Year pillar'],
  'implementation_ids': ['pillars.year_li_chun', 'pillars.month_jie_terms'],
  'page_refs': [{'path': 'output/iching_private_corpus/ba-zi-the-four-pillars-of-destiny.pages.jsonl',
                 'pages': [27, 29]},
                {'path': 'output/iching_private_corpus/bazi-the-destiny-code-your-guide-to-the-four-pillar-of-destin.pages.jsonl',
                 'pages': [53, 55, 56, 57]}],
  'external_refs': [{'id': 'web.hko_24_solar_terms',
                     'url': 'https://www.hko.gov.hk/en/gts/astronomy/Solar_Term.htm',
                     'use': 'Minute-level 24 solar-term reference table; HKO states the data is from HM Nautical '
                            'Almanac Office and USNO.'},
                    {'id': 'web.hko_official_chinese_calendar_year',
                     'url': 'https://www.hko.gov.hk/en/education/astronomy-and-time/time-service/00506-what-year-is-it-today.html',
                     'use': 'Separates the official Chinese-calendar year rollover at Lunar New Year from the '
                            'BaZi Li-Chun Year Pillar convention.'}],
  'curation_status': 'page_and_external_reference_seeded'},
 {'id': 'anchor.pillars.true_solar_late_zi',
  'area': 'true_solar_time',
  'source_id': 'web.noaa_true_solar_time',
  'path': 'https://gml.noaa.gov/grad/solcalc/solareqns.PDF',
  'anchor_type': 'method_reference',
  'keywords': ['equation of time', 'longitude correction', 'true solar time'],
  'implementation_ids': ['pillars.hour_civil_true_solar', 'pillars.late_zi_day_boundary'],
  'page_refs': [{'path': 'output/iching_private_corpus/bazi-the-destiny-code-your-guide-to-the-four-pillar-of-destin.pages.jsonl',
                 'pages': [75],
                 'use': 'Late Zi / Early Rat local-source school-variant anchor.'},
                {'path': 'output/iching_private_corpus_ocr/the-chinese-fortune-telling-system-bazi-method.ocr.pages.jsonl',
                 'pages': [37],
                 'use': 'OCR cross-check for lunar-solar time and hour discussion.'}],
  'external_refs': [{'id': 'web.noaa_true_solar_time',
                     'url': 'https://gml.noaa.gov/grad/solcalc/solareqns.PDF',
                     'use': 'Equation-of-time and longitude correction formula.'},
                    {'id': 'web.usno_equation_of_time',
                     'url': 'https://aa.usno.navy.mil/faq/eqtime',
                     'use': 'Civil time, mean solar time, and apparent solar time distinction.'}],
  'curation_status': 'local_late_zi_and_astronomy_reference_seeded'},
 {'id': 'anchor.ten_gods.five_factors',
  'area': 'ten_gods',
  'source_id': 'local.destiny_code_five_factors',
  'path': 'output/iching_private_corpus/bazi-the-destiny-code-your-guide-to-the-four-pillar-of-destin.md',
  'anchor_type': 'keyword_anchor',
  'keywords': ['Day Master',
               'Ten Gods',
               'Five Factors',
               'Tian Gan',
               'hidden stems',
               'Wealth',
               'Output',
               'Resource',
               'Companion',
               'Influence'],
  'implementation_ids': ['ten_gods.five_factor_profile'],
 'page_refs': [{'path': 'output/iching_private_corpus/bazi-the-destiny-code-your-guide-to-the-four-pillar-of-destin.pages.jsonl',
                 'pages': [139, 140, 141, 142, 143]},
                {'path': 'output/iching_private_corpus/ba-zi-the-four-pillars-of-destiny.pages.jsonl',
                 'pages': [49, 50, 55],
                 'use': 'Local cross-check that Five Factors are read from the Day Master and expanded into Ten Gods with polarity.'},
                {'path': 'output/iching_private_corpus/chinese-astrology.pages.jsonl', 'pages': [11]}],
  'curation_status': 'page_reference_seeded'},
 {'id': 'anchor.life_areas.topic_map',
  'area': 'life_areas',
  'source_id': 'local.destiny_code_revealed_four_aspects',
  'path': 'output/iching_private_corpus/bazi-the-destiny-code-revealed-a-deeper-journey-into-the-four-pillars-of-destiny.md',
  'anchor_type': 'topic_anchor',
  'keywords': ['Career',
               'Wealth',
               'Relationships',
               'Health',
               'Five Factors',
               'Output',
               'Influence',
               'Luck Pillars',
               'Clash',
               'Harm',
               'Punishment'],
  'implementation_ids': ['life_areas.topic_map'],
  'page_refs': [{'path': 'output/iching_private_corpus/bazi-the-destiny-code-revealed-a-deeper-journey-into-the-four-pillars-of-destiny.pages.jsonl',
                 'pages': [426, 427, 428],
                 'use': 'Four Aspects examples require Five Factor condition, timing, and contact context.'},
                {'path': 'output/iching_private_corpus/ba-zi-the-four-pillars-of-destiny.pages.jsonl',
                 'pages': [55, 56, 57],
                 'use': 'Four-pillar palace life-stage and relationship-depth context.'}],
  'curation_status': 'local_and_public_topic_reference_seeded'},
 {'id': 'anchor.strength.roots_season',
  'area': 'strength',
  'source_id': 'local.four_pillars_strength',
  'path': 'output/iching_private_corpus/ba-zi-the-four-pillars-of-destiny.md',
  'anchor_type': 'keyword_anchor',
  'keywords': ['Day Master',
               'season',
               'month branch',
               'root',
               'normal root',
               'secret root',
               'hidden stems',
               'formation',
               'eight palaces',
               'growth',
               'cardinals',
               'graveyards',
               'strength'],
  'implementation_ids': ['strength.season_root_formation'],
  'page_refs': [{'path': 'output/iching_private_corpus/ba-zi-the-four-pillars-of-destiny.pages.jsonl',
                 'pages': [43, 44, 45, 46, 66],
                 'use': 'Augier anchor for hidden stems as root, season as primary strength authority, normal/secret roots, and formation support across eight palaces.'},
                {'path': 'output/iching_private_corpus/bazi-the-destiny-code-your-guide-to-the-four-pillar-of-destin.pages.jsonl',
                 'pages': [140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152]},
                {'path': 'output/iching_private_corpus_ocr/the-chinese-fortune-telling-system-bazi-method.ocr.pages.jsonl',
                 'pages': [46]}],
  'curation_status': 'page_reference_seeded'},
 {'id': 'anchor.pillars.hidden_stems',
  'area': 'pillars',
  'source_id': 'local.four_pillars_strength',
  'path': 'output/iching_private_corpus/ba-zi-the-four-pillars-of-destiny.md',
  'anchor_type': 'keyword_anchor',
  'keywords': ['hidden stems',
               'hidden heavenly stems',
               'major stem',
               'supporting stems',
               'root',
               'Day Master',
               'Earthly Branches',
               'growth',
               'cardinals',
               'graveyards'],
  'implementation_ids': ['pillars.hidden_stems', 'strength.season_root_formation', 'ten_gods.five_factor_profile'],
  'page_refs': [{'path': 'output/iching_private_corpus/ba-zi-the-four-pillars-of-destiny.pages.jsonl',
                 'pages': [44, 45, 66],
                 'use': 'Augier anchor for hidden stems as branch-carried roots and timing-sensitive human-level material.'}],
  'curation_status': 'page_reference_seeded'},
 {'id': 'anchor.relationships.codes',
  'area': 'relationships',
  'source_id': 'local.destiny_code_revealed_relationships',
  'path': 'output/iching_private_corpus/bazi-the-destiny-code-revealed-a-deeper-journey-into-the-four-pillars-of-destiny.md',
  'anchor_type': 'keyword_anchor',
  'keywords': ['combination', 'clash', 'harm', 'punishment', 'destruction', 'spouse palace'],
  'implementation_ids': ['relationships.codes', 'relationships.spouse_palace'],
  'page_refs': [{'path': 'output/iching_private_corpus/bazi-the-destiny-code-revealed-a-deeper-journey-into-the-four-pillars-of-destiny.pages.jsonl',
                 'pages': [89,
                           90,
                           91,
                           92,
                           93,
                           94,
                           95,
                           96,
                           97,
                           98,
                           99,
                           100,
                           101,
                           111,
                           127,
                           202,
                           216,
                           223,
                           228,
                           229,
                           230]},
                {'path': 'output/iching_private_corpus_ocr/the-chinese-fortune-telling-system-bazi-method.ocr.pages.jsonl',
                 'pages': [72, 76, 77, 78]}],
  'external_refs': [{'id': 'web.destinyi_compatibility',
                     'url': 'https://destinyi.com/encyclopedia/bazi/bazi-compatibility-explained',
                     'use': 'Modern compatibility cross-check for balancing contacts, Ten Gods, element condition, and '
                            'timing.'}],
  'curation_status': 'page_reference_seeded_needs_qualitative_pair_calibration'},
 {'id': 'anchor.timing.luck_pillars',
  'area': 'timing',
  'source_id': 'local.four_pillars_strength',
  'path': 'output/iching_private_corpus/ba-zi-the-four-pillars-of-destiny.md',
  'anchor_type': 'keyword_anchor',
  'keywords': ['Luck Pillar',
               'forward',
               'reverse',
               'start age',
               'solar term',
               'month pillar sequence',
               'same as birth pillar',
               'time of change'],
  'implementation_ids': ['luck_pillars.direction_start_age', 'timing.rhythm_layers'],
  'page_refs': [{'path': 'output/iching_private_corpus/bazi-the-destiny-code-your-guide-to-the-four-pillar-of-destin.pages.jsonl',
                 'pages': [87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98]},
                {'path': 'output/iching_private_corpus/ba-zi-the-four-pillars-of-destiny.pages.jsonl',
                 'pages': [46, 47, 48]},
                {'path': 'output/iching_private_corpus_ocr/the-chinese-fortune-telling-system-bazi-method.ocr.pages.jsonl',
                 'pages': [44, 45]}],
 'external_refs': [{'id': 'web.wikibooks_luck_pillar',
                     'url': 'https://en.wikibooks.org/wiki/Ba_Zi/Luck_Pillar',
                     'use': 'Open cross-check for forward/reverse direction and three-days-per-year start-age '
                            'method.'}],
  'curation_status': 'page_and_variant_reference_seeded'},
 {'id': 'anchor.timing.growth_stages',
  'area': 'timing',
  'source_id': 'local.four_pillars_growth_stages',
  'path': 'output/iching_private_corpus/ba-zi-the-four-pillars-of-destiny.md',
  'anchor_type': 'table_anchor',
  'keywords': ['12 stages', 'growth stage', 'Chang Sheng', 'Di Wang', 'Tomb'],
  'implementation_ids': ['timing.rhythm_layers'],
  'page_refs': [{'path': 'output/iching_private_corpus/ba-zi-the-four-pillars-of-destiny.pages.jsonl',
                 'pages': [63],
                 'use': 'Local 12-growth-stage table used for Day Master qi-state against timing branches.'}],
  'external_refs': [{'id': 'web.imperial_harvest_12_stages',
                     'url': 'https://imperialharvest.com/blog/the-12-stages-of-growth/',
                     'use': 'Public cross-check that the 12 stages are a BaZi strength/qi-state concept.'}],
  'curation_status': 'page_reference_seeded_needs_fixture_expansion'},
 {'id': 'anchor.useful_elements.climate_damage',
  'area': 'useful_elements',
  'source_id': 'local.destiny_code_damaged_useful_element',
  'path': 'output/iching_private_corpus/bazi-the-destiny-code-revealed-a-deeper-journey-into-the-four-pillars-of-destiny.md',
  'anchor_type': 'keyword_anchor',
  'keywords': ['favorable element', 'useful god', 'Yong Shen', 'climate', 'season', 'damage'],
  'implementation_ids': ['useful_elements.preview'],
  'page_refs': [{'path': 'output/iching_private_corpus/bazi-the-destiny-code-your-guide-to-the-four-pillar-of-destin.pages.jsonl',
                 'pages': [139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 277, 283, 286]},
                {'path': 'output/iching_private_corpus_ocr/the-chinese-fortune-telling-system-bazi-method.ocr.pages.jsonl',
                 'pages': [45, 46, 72]}],
  'external_refs': [{'id': 'web.bazi8_strength_useful',
                     'url': 'https://bazi8.net/learn/self-strength',
                     'use': 'Modern cross-check for strength, useful god, and climate override boundaries.'},
                    {'id': 'web.zodiaczen_strength_useful',
                     'url': 'https://zodiaczen.cc/learn/bazi/strong-weak-day-master/',
                     'use': 'Modern cross-check that useful elements depend on structure, not simple counts.'}],
  'curation_status': 'page_reference_seeded_needs_final_yong_shen_fixtures'},
 {'id': 'anchor.auxiliary.peach_blossom',
  'area': 'auxiliary_stars',
  'source_id': 'local.destiny_code_peach_blossom',
  'path': 'output/iching_private_corpus/bazi-the-destiny-code-your-guide-to-the-four-pillar-of-destin.md',
  'anchor_type': 'keyword_anchor',
  'keywords': ['Peach Blossom', 'Day Branch', 'attraction', 'popularity'],
  'implementation_ids': ['auxiliary.shen_sha_markers'],
  'page_refs': [{'path': 'output/iching_private_corpus/bazi-the-destiny-code-revealed-a-deeper-journey-into-the-four-pillars-of-destiny.pages.jsonl',
                 'pages': [228, 229, 230]}],
  'curation_status': 'page_reference_seeded_needs_more_auxiliary_examples'}]

GOLDEN_FIXTURE_MANIFEST: List[Dict[str, Any]] = [{'id': 'year_li_chun_before_after_2000',
  'area': 'solar_terms',
  'status': 'implemented',
  'coverage': 'Year pillar changes from Ji Mao to Geng Chen across Li Chun.'},
 {'id': 'month_jing_zhe_before_after_2000',
  'area': 'solar_terms',
  'status': 'implemented',
  'coverage': 'Month branch changes from Yin to Mao across Jing Zhe.'},
 {'id': 'civil_hour_zi_chou_boundary',
  'area': 'hour_pillar',
  'status': 'implemented',
  'coverage': 'Civil hour branch changes from Zi to Chou across the 01:00 boundary.'},
 {'id': 'true_solar_hour_flip_utc_longitude_45',
  'area': 'true_solar_time',
  'status': 'implemented',
  'coverage': 'True solar mode can change the selected hour pillar when longitude correction crosses a branch window.'},
 {'id': 'true_solar_day_boundary_flip_utc_longitude_minus_45',
  'area': 'true_solar_time',
  'status': 'implemented',
  'coverage': 'True-solar day-boundary mode can change the selected Day Pillar when longitude correction crosses '
              'midnight.'},
 {'id': 'late_zi_next_day_variant',
  'area': 'hour_pillar',
  'status': 'implemented',
  'coverage': 'Late Zi-hour next-day mode advances the Day Pillar for 23:00-23:59 births.'},
 {'id': 'unknown_birth_time_hour_withheld',
  'area': 'missing_inputs',
  'status': 'implemented',
  'coverage': 'Unknown time keeps year/month/day available while withholding hour pillar.'},
 {'id': 'luck_direction_yang_male_yin_female',
  'area': 'luck_pillars',
  'status': 'implemented',
  'coverage': 'Yang-year male and yin-year female use forward direction; opposite combinations reverse.'},
 {'id': 'luck_direction_variant_payload',
  'area': 'luck_pillars',
  'status': 'implemented',
  'coverage': 'Luck direction payload exposes the selected polarity source and rule key.'},
 {'id': 'relationship_code_fixture_matrix_seed',
  'area': 'relationships',
  'status': 'implemented',
  'coverage': 'Fixture matrix covers every configured relationship-code event type at least once.'},
 {'id': 'pair_spouse_palace_score_seed',
  'area': 'compatibility',
  'status': 'implemented_seed',
  'coverage': 'Two-snap compatibility returns spouse-palace, Day Master exchange, timing, useful-element, and score '
              'components.'},
 {'id': 'useful_elements_climate_damage_seed',
  'area': 'useful_elements',
  'status': 'implemented_seed',
  'coverage': 'Useful-element payload includes climate/regulating candidates, damaged-useful assessment, and final '
              'Yong Shen withholding.'},
 {'id': 'source_anchor_manifest_seed',
  'area': 'source_curation',
  'status': 'implemented_seed',
  'coverage': 'Rule-note source anchors map implementation ids to private corpus paths, web references, and curation '
              'status.'}]

CURATION_BACKLOG_IDS: List[str] = ['pillars.hour_civil_true_solar', 'strength.season_root_formation', 'useful_elements.preview', 'useful_elements.yong_shen_rule_families']


def confidence_tags(*keys: str) -> List[Dict[str, str]]:
    tags: List[Dict[str, str]] = []
    for key in keys:
        template = SOURCE_CONFIDENCE_LABELS.get(key)
        if template:
            tags.append(dict(template))
        else:
            tags.append({
                "key": key,
                "label": str(key).replace("_", " ").title(),
                "description": "Unregistered source confidence tag.",
            })
    return tags


def rule_notes_for_areas(areas: Iterable[str]) -> List[Dict[str, Any]]:
    selected = set(areas or [])
    return [note for note in RULE_NOTES if note.get("area") in selected]


def curation_summary() -> Dict[str, Any]:
    return {
        "status": "phase_5_6_curation_and_workflow_foundation",
        "rule_note_count": len(RULE_NOTES),
        "fixture_count": len(GOLDEN_FIXTURE_MANIFEST),
        "source_anchor_count": len(SOURCE_ANCHORS),
        "needs_validation": list(CURATION_BACKLOG_IDS),
        "validation": validation_summary(),
        "source_confidence_labels": [dict(item) for item in SOURCE_CONFIDENCE_LABELS.values()],
        "fixture_manifest": GOLDEN_FIXTURE_MANIFEST,
        "source_anchors": SOURCE_ANCHORS,
    }
