import json
from datetime import datetime, timezone
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
FORENSIC_TEXT_DIR = REPO_ROOT / "extracted_text_docs" / "text_forensics"
OUTPUT_PATH = REPO_ROOT / "tests" / "fixtures" / "forensic_case_corpus.json"


def _case(
    *,
    case_id: str,
    title: str,
    book_id: str,
    source_file: str,
    source_section: str,
    case_family: str,
    expected_primary_axes,
    expected_secondary_axes=None,
    contradictory_axes=None,
    label_basis: str = "title_and_book_context",
    label_confidence: str = "medium",
    notes: str = "",
    execution_tier: str = "tier_1_directional_seed",
    chart_capture_status: str = "needs_chart_capture",
):
    return {
        "id": case_id,
        "title": title,
        "entry_kind": "case_seed",
        "book_id": book_id,
        "source_file": source_file,
        "source_section": source_section,
        "case_family": case_family,
        "expected_primary_axes": list(expected_primary_axes),
        "expected_secondary_axes": list(expected_secondary_axes or []),
        "contradictory_axes": list(contradictory_axes or []),
        "label_basis": label_basis,
        "label_confidence": label_confidence,
        "execution_tier": execution_tier,
        "chart_capture_status": chart_capture_status,
        "comparison_status": "not_runnable_yet",
        "notes": notes,
    }


def build_corpus():
    stars_file = "Forensics by the Stars Astrology Investigates (B. D. Salerno) (Z-Library).txt"
    family_file = "Exploring Forensic Astrology The Secrets Behind Famous Family Murders (B. D. Salerno) (Z-Library).txt"
    luley_file = "Forensic Astrology for Everyone You Dont Need to be an Astrologer to Locate Lost Objects, Find Missing Persons, Solve… (Caroline J. Luley) (Z-Library).txt"

    sources = [
        {
            "id": "salerno_forensics_by_the_stars",
            "kind": "case_book",
            "title": "Forensics by the Stars: Astrology Investigates",
            "author": "B. D. Salerno",
            "source_file": str(FORENSIC_TEXT_DIR / stars_file),
            "use": "event-case seeds and replay promotion",
        },
        {
            "id": "salerno_exploring_family_murders",
            "kind": "case_book",
            "title": "Exploring Forensic Astrology: The Secrets Behind Famous Family Murders",
            "author": "B. D. Salerno",
            "source_file": str(FORENSIC_TEXT_DIR / family_file),
            "use": "family homicide, domestic, filicide, parricide, familicide, friend cases",
        },
        {
            "id": "luley_forensic_astrology_for_everyone",
            "kind": "methodology",
            "title": "Forensic Astrology for Everyone",
            "author": "Caroline J. Luley",
            "source_file": str(FORENSIC_TEXT_DIR / luley_file),
            "use": "taxonomy, lost-object/missing-person methodology, timing and movement framework",
        },
    ]

    cases = [
        _case(
            case_id="lindbergh_kidnapping",
            title="The Lindbergh Kidnapping",
            book_id="salerno_forensics_by_the_stars",
            source_file=stars_file,
            source_section="Chapter One",
            case_family="kidnapping",
            expected_primary_axes=["abduction_missing_person", "child_victim", "violence_homicide"],
            expected_secondary_axes=["deception_coverup"],
            notes="Seed from explicit case title and opening chapter summary.",
        ),
        _case(
            case_id="marilyn_monroe_murder",
            title="The Murder of Marilyn Monroe",
            book_id="salerno_forensics_by_the_stars",
            source_file=stars_file,
            source_section="Chapter Two",
            case_family="suspicious_death",
            expected_primary_axes=["violence_homicide", "authority_or_public_case"],
            expected_secondary_axes=["deception_coverup"],
            contradictory_axes=["accident_or_disaster"],
        ),
        _case(
            case_id="ronnie_lee_bakley",
            title="Ronnie Lee Bakley: Death by Beretta?",
            book_id="salerno_exploring_family_murders",
            source_file=family_file,
            source_section="Mariticide",
            case_family="spousal_murder",
            expected_primary_axes=["violence_homicide", "domestic_partner_involvement"],
            expected_secondary_axes=["authority_or_public_case", "deception_coverup"],
        ),
        _case(
            case_id="phil_hartman",
            title="Phil Hartman: Murder by Wife",
            book_id="salerno_exploring_family_murders",
            source_file=family_file,
            source_section="Mariticide",
            case_family="spousal_murder",
            expected_primary_axes=["violence_homicide", "domestic_partner_involvement"],
            expected_secondary_axes=["family_involvement"],
            label_confidence="high",
        ),
        _case(
            case_id="natalie_wood",
            title="Natalie Wood: A Farewell to Splendor",
            book_id="salerno_exploring_family_murders",
            source_file=family_file,
            source_section="Mariticide",
            case_family="suspicious_water_death",
            expected_primary_axes=["water_disappearance_or_drowning", "violence_homicide"],
            expected_secondary_axes=["domestic_partner_involvement", "authority_or_public_case"],
            contradictory_axes=["accident_or_disaster"],
            notes="Book introduction frames this as sudden violence rather than pure accident.",
        ),
        _case(
            case_id="scott_peterson",
            title="Scott Peterson: A Talent for Deception",
            book_id="salerno_exploring_family_murders",
            source_file=family_file,
            source_section="Mariticide",
            case_family="spousal_murder",
            expected_primary_axes=["deception_coverup", "domestic_partner_involvement", "violence_homicide"],
            expected_secondary_axes=["authority_or_public_case"],
            label_confidence="high",
        ),
        _case(
            case_id="sam_sheppard",
            title="The Sam Sheppard Case",
            book_id="salerno_exploring_family_murders",
            source_file=family_file,
            source_section="Mariticide",
            case_family="spousal_murder_disputed",
            expected_primary_axes=["violence_homicide", "domestic_partner_involvement"],
            expected_secondary_axes=["deception_coverup"],
            label_confidence="low",
            execution_tier="tier_3_manual_review",
            notes="Useful later for false-accusation/exoneration analysis; not a clean starter alignment case.",
        ),
        _case(
            case_id="andrea_yates",
            title="Andrea Yates: Closer to God?",
            book_id="salerno_exploring_family_murders",
            source_file=family_file,
            source_section="Filicide",
            case_family="filicide",
            expected_primary_axes=["family_involvement", "child_victim", "violence_homicide"],
            expected_secondary_axes=["deception_coverup"],
        ),
        _case(
            case_id="marvin_gaye",
            title="Marvin Gaye: Death by Father",
            book_id="salerno_exploring_family_murders",
            source_file=family_file,
            source_section="Filicide",
            case_family="family_homicide",
            expected_primary_axes=["family_involvement", "violence_homicide", "authority_or_public_case"],
            expected_secondary_axes=["domestic_partner_involvement"],
        ),
        _case(
            case_id="jonbenet_ramsey",
            title="JonBenet Ramsey and the Killing Planet",
            book_id="salerno_exploring_family_murders",
            source_file=family_file,
            source_section="Filicide",
            case_family="child_homicide",
            expected_primary_axes=["child_victim", "family_involvement", "violence_homicide"],
            expected_secondary_axes=["deception_coverup", "authority_or_public_case"],
            label_confidence="high",
        ),
        _case(
            case_id="diane_downs",
            title="Diane Downs: Murder by Mother",
            book_id="salerno_exploring_family_murders",
            source_file=family_file,
            source_section="Filicide",
            case_family="filicide",
            expected_primary_axes=["family_involvement", "child_victim", "violence_homicide"],
            expected_secondary_axes=["deception_coverup"],
        ),
        _case(
            case_id="darlie_routier",
            title="Darlie Routier: The Greater Part of Them",
            book_id="salerno_exploring_family_murders",
            source_file=family_file,
            source_section="Filicide",
            case_family="filicide",
            expected_primary_axes=["family_involvement", "child_victim", "violence_homicide"],
            expected_secondary_axes=["deception_coverup"],
        ),
        _case(
            case_id="alice_crimmins",
            title="Alice Crimmins: Guilty by Lifestyle?",
            book_id="salerno_exploring_family_murders",
            source_file=family_file,
            source_section="Filicide",
            case_family="child_murder_disputed",
            expected_primary_axes=["family_involvement", "child_victim"],
            expected_secondary_axes=["deception_coverup"],
            label_confidence="low",
            execution_tier="tier_3_manual_review",
        ),
        _case(
            case_id="susan_smith",
            title="Susan Smith: Anything for Love",
            book_id="salerno_exploring_family_murders",
            source_file=family_file,
            source_section="Filicide",
            case_family="filicide",
            expected_primary_axes=["family_involvement", "child_victim", "deception_coverup", "violence_homicide"],
            label_confidence="high",
        ),
        _case(
            case_id="lizzie_borden",
            title="Lizzie Borden Took an Ax",
            book_id="salerno_exploring_family_murders",
            source_file=family_file,
            source_section="Parricide",
            case_family="parricide",
            expected_primary_axes=["family_involvement", "violence_homicide"],
            expected_secondary_axes=["deception_coverup"],
        ),
        _case(
            case_id="menendez_brothers",
            title="The Menendez Brothers: Implacable Hatred",
            book_id="salerno_exploring_family_murders",
            source_file=family_file,
            source_section="Parricide",
            case_family="parricide",
            expected_primary_axes=["family_involvement", "violence_homicide", "accomplice_or_witness"],
            expected_secondary_axes=["deception_coverup"],
        ),
        _case(
            case_id="charles_whitman",
            title="Charles Whitman, the Tower Sniper",
            book_id="salerno_exploring_family_murders",
            source_file=family_file,
            source_section="Parricide",
            case_family="public_violence",
            expected_primary_axes=["violence_homicide", "authority_or_public_case"],
            expected_secondary_axes=["family_involvement"],
        ),
        _case(
            case_id="john_list",
            title="John List: The Bogeyman of Westfield",
            book_id="salerno_exploring_family_murders",
            source_file=family_file,
            source_section="Familicide",
            case_family="familicide",
            expected_primary_axes=["family_involvement", "violence_homicide", "deception_coverup"],
            label_confidence="high",
        ),
        _case(
            case_id="amityville_defeo",
            title="Butch DeFeo and the Amityville Murders: From High Hopes to Horror",
            book_id="salerno_exploring_family_murders",
            source_file=family_file,
            source_section="Familicide",
            case_family="familicide",
            expected_primary_axes=["family_involvement", "violence_homicide"],
            expected_secondary_axes=["deception_coverup"],
        ),
        _case(
            case_id="bob_crane",
            title="Bob Crane: Was His Best Friend Guilty?",
            book_id="salerno_exploring_family_murders",
            source_file=family_file,
            source_section="Murder by Friend",
            case_family="friend_homicide",
            expected_primary_axes=["friend_or_close_associate", "violence_homicide"],
            expected_secondary_axes=["deception_coverup", "authority_or_public_case"],
        ),
        _case(
            case_id="gianni_versace",
            title="Did Gianni Versace Know His Killer?",
            book_id="salerno_exploring_family_murders",
            source_file=family_file,
            source_section="Murder by Friend",
            case_family="celebrity_homicide",
            expected_primary_axes=["violence_homicide", "authority_or_public_case"],
            expected_secondary_axes=["friend_or_close_associate"],
        ),
    ]

    return {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "purpose": "Starter labeled corpus for forensic feature directional evaluation",
        "comparison_axes": [
            "violence_homicide",
            "abduction_missing_person",
            "deception_coverup",
            "domestic_partner_involvement",
            "family_involvement",
            "child_victim",
            "water_disappearance_or_drowning",
            "accident_or_disaster",
            "friend_or_close_associate",
            "authority_or_public_case",
            "accomplice_or_witness",
        ],
        "sources": sources,
        "cases": cases,
    }


def main():
    corpus = build_corpus()
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(json.dumps(corpus, indent=2, ensure_ascii=True), encoding="utf-8")
    print(f"Wrote {len(corpus['cases'])} forensic cases to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
