from __future__ import annotations

from typing import Any, Dict, Iterable, List, Optional

VALIDATION_PHASES: List[Dict[str, Any]] = [{'id': 'V1',
  'title': 'Calendar And Pillar Correctness',
  'priority': 'P0',
  'status': 'fixture_ledger_seeded',
  'areas': ['solar_terms', 'day_cycle', 'hour_pillar', 'true_solar_time'],
  'goal': 'Prove deterministic year, month, day, and hour pillar calculations before deeper interpretation.'},
 {'id': 'V2',
  'title': 'Timing And School Variants',
  'priority': 'P0',
  'status': 'fixture_ledger_seeded',
  'areas': ['true_solar_time', 'late_zi', 'luck_pillars', 'timing_rhythm'],
  'goal': 'Keep true-solar, late-Zi, Luck Direction, and BaZi timing-rhythm variants auditable and explicit.'},
 {'id': 'V3',
  'title': 'Strength Useful Elements And Yong Shen',
  'priority': 'P1',
  'status': 'fixture_ledger_seeded',
  'areas': ['strength', 'useful_elements', 'special_structures'],
  'goal': 'Validate strength and useful-element guidance while final Yong Shen remains withheld.'},
 {'id': 'V4',
  'title': 'Relationship Palace Auxiliary And Pair Calibration',
  'priority': 'P1',
  'status': 'fixture_ledger_seeded',
  'areas': ['relationships', 'palaces', 'auxiliary_stars', 'compatibility'],
  'goal': 'Calibrate relationship-code tone, palace placement, Peach Blossom, and pair scoring.'},
 {'id': 'V5',
  'title': 'Frontend Workflow And UX QA',
  'priority': 'P1',
  'status': 'component_coverage_seeded',
  'areas': ['frontend_workflow', 'saved_snaps', 'reading_history', 'mobile_qa'],
  'goal': 'Exercise the Astro Clock workspace pattern under real saved-chart and pair-selection flows.'},
 {'id': 'V6',
  'title': 'Release Gate',
  'priority': 'P0',
  'status': 'command_gate_defined',
  'areas': ['release', 'packaging', 'version_metadata'],
  'goal': 'Require focused backend/frontend tests, build, and packaged-app smoke checks before release.'},
 {'id': 'V7',
  'title': 'I Ching Oracle',
  'priority': 'P1',
  'status': 'source_backed_module_seeded',
  'areas': ['iching_oracle', 'hexagrams', 'changing_lines', 'source_evidence'],
  'goal': 'Validate the standalone Oracle engine, line order, changing-line derivation, King Wen resolution, and source evidence UI.'}]

VALIDATION_FIXTURES: List[Dict[str, Any]] = [{'id': 'solar_terms.hko_2026_jie_reference_set',
  'phase': 'V1',
  'priority': 'P0',
  'area': 'solar_terms',
  'kind': 'solar_term_reference_set',
  'source_anchor': 'web.hko_24_solar_terms',
  'source_reference_status': 'external_hko_hm_nautical_usno_anchored',
  'input': {'year': 2026},
  'tolerance_seconds': 90,
  'expected_terms_utc': {'xiao_han': '2026-01-05T08:23:00+00:00',
                         'li_chun': '2026-02-03T20:02:00+00:00',
                         'jing_zhe': '2026-03-05T13:59:00+00:00',
                         'qing_ming': '2026-04-04T18:40:00+00:00',
                         'li_xia': '2026-05-05T11:49:00+00:00',
                         'mang_zhong': '2026-06-05T15:48:00+00:00',
                         'xiao_shu': '2026-07-07T01:57:00+00:00',
                         'li_qiu': '2026-08-07T11:43:00+00:00',
                         'bai_lu': '2026-09-07T14:41:00+00:00',
                         'han_lu': '2026-10-08T06:29:00+00:00',
                         'li_dong': '2026-11-07T09:52:00+00:00',
                         'da_xue': '2026-12-07T02:53:00+00:00'},
  'notes': 'HKO publishes 24 solar-term times in Hong Kong Time; these UTC values subtract eight hours and keep '
           'minute-level tolerance for rounding.'},
 {'id': 'calendar.li_chun_1999_before',
  'phase': 'V1',
  'priority': 'P0',
  'area': 'solar_terms',
  'kind': 'profile',
  'source_anchor': 'anchor.pillars.li_chun_jie_terms',
  'source_reference_status': 'implementation_seed_needs_almanac_anchor',
  'input': {'datetime_utc': '1999-02-03T12:00:00+00:00', 'timezone': 'UTC'},
  'options': {'calculation_sex': 'female', 'include_luck_pillars': True},
  'expected': {'pillars': {'year': 'Wu Yin', 'month': 'Yi Chou'},
               'paths': {'debug.bazi_year': 1998, 'debug.month_solar_term.key': 'xiao_han'}}},
 {'id': 'calendar.li_chun_1999_after',
  'phase': 'V1',
  'priority': 'P0',
  'area': 'solar_terms',
  'kind': 'profile',
  'source_anchor': 'anchor.pillars.li_chun_jie_terms',
  'source_reference_status': 'implementation_seed_needs_almanac_anchor',
  'input': {'datetime_utc': '1999-02-06T12:00:00+00:00', 'timezone': 'UTC'},
  'options': {'calculation_sex': 'female', 'include_luck_pillars': True},
  'expected': {'pillars': {'year': 'Ji Mao', 'month': 'Bing Yin'},
               'paths': {'debug.bazi_year': 1999, 'debug.month_solar_term.key': 'li_chun'}}},
 {'id': 'calendar.li_chun_2000_before',
  'phase': 'V1',
  'priority': 'P0',
  'area': 'solar_terms',
  'kind': 'profile',
  'source_anchor': 'anchor.pillars.li_chun_jie_terms',
  'source_reference_status': 'seed_verified_by_existing_test',
  'input': {'datetime_utc': '2000-02-03T12:00:00+00:00', 'timezone': 'UTC'},
  'expected': {'pillars': {'year': 'Ji Mao', 'month': 'Ding Chou'},
               'paths': {'debug.bazi_year': 1999, 'debug.month_solar_term.key': 'xiao_han'}}},
 {'id': 'calendar.li_chun_2000_after',
  'phase': 'V1',
  'priority': 'P0',
  'area': 'solar_terms',
  'kind': 'profile',
  'source_anchor': 'anchor.pillars.li_chun_jie_terms',
  'source_reference_status': 'seed_verified_by_existing_test',
  'input': {'datetime_utc': '2000-02-06T12:00:00+00:00', 'timezone': 'UTC'},
  'expected': {'pillars': {'year': 'Geng Chen', 'month': 'Wu Yin'},
               'paths': {'debug.bazi_year': 2000, 'debug.month_solar_term.key': 'li_chun'}}},
 {'id': 'calendar.li_chun_2001_before',
  'phase': 'V1',
  'priority': 'P0',
  'area': 'solar_terms',
  'kind': 'profile',
  'source_anchor': 'anchor.pillars.li_chun_jie_terms',
  'source_reference_status': 'implementation_seed_needs_almanac_anchor',
  'input': {'datetime_utc': '2001-02-03T12:00:00+00:00', 'timezone': 'UTC'},
  'expected': {'pillars': {'year': 'Geng Chen', 'month': 'Ji Chou'},
               'paths': {'debug.bazi_year': 2000, 'debug.month_solar_term.key': 'xiao_han'}}},
 {'id': 'calendar.li_chun_2001_after',
  'phase': 'V1',
  'priority': 'P0',
  'area': 'solar_terms',
  'kind': 'profile',
  'source_anchor': 'anchor.pillars.li_chun_jie_terms',
  'source_reference_status': 'implementation_seed_needs_almanac_anchor',
  'input': {'datetime_utc': '2001-02-06T12:00:00+00:00', 'timezone': 'UTC'},
  'expected': {'pillars': {'year': 'Xin Si', 'month': 'Geng Yin'},
               'paths': {'debug.bazi_year': 2001, 'debug.month_solar_term.key': 'li_chun'}}},
 {'id': 'calendar.jing_zhe_2000_before',
  'phase': 'V1',
  'priority': 'P0',
  'area': 'solar_terms',
  'kind': 'profile',
  'source_anchor': 'anchor.pillars.li_chun_jie_terms',
  'source_reference_status': 'seed_verified_by_existing_test',
  'input': {'datetime_utc': '2000-03-04T12:00:00+00:00', 'timezone': 'UTC'},
  'expected': {'pillars': {'month': 'Wu Yin'}, 'paths': {'debug.month_solar_term.key': 'li_chun'}}},
 {'id': 'calendar.jing_zhe_2000_after',
  'phase': 'V1',
  'priority': 'P0',
  'area': 'solar_terms',
  'kind': 'profile',
  'source_anchor': 'anchor.pillars.li_chun_jie_terms',
  'source_reference_status': 'seed_verified_by_existing_test',
  'input': {'datetime_utc': '2000-03-07T12:00:00+00:00', 'timezone': 'UTC'},
  'expected': {'pillars': {'month': 'Ji Mao'}, 'paths': {'debug.month_solar_term.key': 'jing_zhe'}}},
 {'id': 'calendar.qing_ming_2000_before',
  'phase': 'V1',
  'priority': 'P0',
  'area': 'solar_terms',
  'kind': 'profile',
  'source_anchor': 'anchor.pillars.li_chun_jie_terms',
  'source_reference_status': 'implementation_seed_needs_almanac_anchor',
  'input': {'datetime_utc': '2000-04-03T12:00:00+00:00', 'timezone': 'UTC'},
  'expected': {'pillars': {'month': 'Ji Mao'}, 'paths': {'debug.month_solar_term.key': 'jing_zhe'}}},
 {'id': 'calendar.qing_ming_2000_after',
  'phase': 'V1',
  'priority': 'P0',
  'area': 'solar_terms',
  'kind': 'profile',
  'source_anchor': 'anchor.pillars.li_chun_jie_terms',
  'source_reference_status': 'implementation_seed_needs_almanac_anchor',
  'input': {'datetime_utc': '2000-04-06T12:00:00+00:00', 'timezone': 'UTC'},
  'expected': {'pillars': {'month': 'Geng Chen'}, 'paths': {'debug.month_solar_term.key': 'qing_ming'}}},
 {'id': 'day_cycle.1984_02_03_anchor',
  'phase': 'V1',
  'priority': 'P0',
  'area': 'day_cycle',
  'kind': 'day_cycle',
  'source_anchor': 'source_anchor_manifest_seed',
  'source_reference_status': 'seed_verified_by_existing_test',
  'input': {'date': '1984-02-03'},
  'expected': {'day': 'Ding Mao'}},
 {'id': 'day_cycle.2000_01_01_anchor',
  'phase': 'V1',
  'priority': 'P0',
  'area': 'day_cycle',
  'kind': 'day_cycle',
  'source_anchor': 'source_anchor_manifest_seed',
  'source_reference_status': 'seed_verified_by_existing_test',
  'input': {'date': '2000-01-01'},
  'expected': {'day': 'Wu Wu'}},
 {'id': 'hour.civil_zi',
  'phase': 'V1',
  'priority': 'P0',
  'area': 'hour_pillar',
  'kind': 'profile',
  'source_anchor': 'anchor.pillars.true_solar_late_zi',
  'source_reference_status': 'seed_verified_by_existing_test',
  'input': {'datetime_utc': '2000-01-01T00:30:00+00:00', 'timezone': 'UTC'},
  'expected': {'pillars': {'hour': 'Ren Zi'}, 'paths': {'debug.hour_pillar_comparison.mode': 'civil_local_time'}}},
 {'id': 'hour.civil_chou',
  'phase': 'V1',
  'priority': 'P0',
  'area': 'hour_pillar',
  'kind': 'profile',
  'source_anchor': 'anchor.pillars.true_solar_late_zi',
  'source_reference_status': 'seed_verified_by_existing_test',
  'input': {'datetime_utc': '2000-01-01T01:30:00+00:00', 'timezone': 'UTC'},
  'expected': {'pillars': {'hour': 'Gui Chou'}, 'paths': {'debug.hour_pillar_comparison.mode': 'civil_local_time'}}},
 {'id': 'hour.unknown_time_withheld',
  'phase': 'V1',
  'priority': 'P0',
  'area': 'hour_pillar',
  'kind': 'profile',
  'source_anchor': 'source_anchor_manifest_seed',
  'source_reference_status': 'seed_verified_by_existing_test',
  'input': {'datetime_utc': '2000-01-01T12:00:00+00:00', 'timezone': 'UTC', 'hour_known': False},
  'expected': {'pillars': {'hour': None},
               'paths': {'birth.time_precision': 'unknown'},
               'warnings_contain': ['Birth time is unknown']}},
 {'id': 'true_solar.hour_east_longitude_flip',
  'phase': 'V1',
  'priority': 'P0',
  'area': 'true_solar_time',
  'kind': 'profile',
  'source_anchor': 'anchor.pillars.true_solar_late_zi',
  'source_reference_status': 'seed_verified_by_existing_test',
  'input': {'datetime_utc': '2000-01-01T00:30:00+00:00', 'timezone': 'UTC', 'longitude': 45.0},
  'options': {'use_true_solar_time': True},
  'expected': {'pillars': {'hour': 'Jia Yin'},
               'paths': {'birth.true_solar_time.applied': True,
                         'debug.hour_pillar_comparison.changed': True,
                         'debug.hour_pillar_comparison.mode': 'true_solar_time'}}},
 {'id': 'true_solar.day_boundary_west_longitude_flip',
  'phase': 'V2',
  'priority': 'P0',
  'area': 'true_solar_time',
  'kind': 'profile',
  'source_anchor': 'anchor.pillars.true_solar_late_zi',
  'source_reference_status': 'local_variant_and_astronomy_reference_seeded_needs_doctrine_example',
  'input': {'datetime_utc': '2000-01-01T00:30:00+00:00', 'timezone': 'UTC', 'longitude': -45.0},
  'options': {'day_boundary_rule': 'true_solar_midnight'},
  'expected': {'pillars': {'day': 'Ding Si'},
               'paths': {'birth.day_basis.basis': 'true_solar_time',
                         'birth.day_basis.date': '1999-12-31',
                         'debug.day_pillar_comparison.changed': True}}},
 {'id': 'late_zi.next_day_variant',
  'phase': 'V2',
  'priority': 'P0',
  'area': 'late_zi',
  'kind': 'profile',
  'source_anchor': 'anchor.pillars.true_solar_late_zi',
  'source_reference_status': 'local_late_zi_page_anchor_seeded',
  'input': {'datetime_utc': '2000-01-01T23:30:00+00:00', 'timezone': 'UTC'},
  'options': {'hour_pillar_variant': 'late_zi_next_day'},
  'expected': {'pillars': {'day': 'Ji Wei'},
               'paths': {'birth.day_basis.date': '2000-01-02',
                         'debug.day_pillar_comparison.late_zi_next_day_applied': True},
               'warnings_contain': ['Late Zi-hour next-day variant is applied']}},
 {'id': 'luck.direction_year_stem_yang_male',
  'phase': 'V2',
  'priority': 'P0',
  'area': 'luck_pillars',
  'kind': 'profile',
  'source_anchor': 'anchor.timing.luck_pillars',
  'source_reference_status': 'seed_verified_by_existing_test',
  'input': {'datetime_utc': '2000-02-06T12:00:00+00:00', 'timezone': 'UTC'},
  'options': {'calculation_sex': 'male', 'include_luck_pillars': True},
  'expected': {'paths': {'timing.direction': 'forward', 'timing.direction_rule_key': 'year_stem_polarity'}}},
 {'id': 'luck.direction_year_stem_yang_female',
  'phase': 'V2',
  'priority': 'P0',
  'area': 'luck_pillars',
  'kind': 'profile',
  'source_anchor': 'anchor.timing.luck_pillars',
  'source_reference_status': 'seed_verified_by_existing_test',
  'input': {'datetime_utc': '2000-02-06T12:00:00+00:00', 'timezone': 'UTC'},
  'options': {'calculation_sex': 'female', 'include_luck_pillars': True},
  'expected': {'paths': {'timing.direction': 'reverse', 'timing.direction_rule_key': 'year_stem_polarity'}}},
 {'id': 'luck.direction_day_stem_variant',
  'phase': 'V2',
  'priority': 'P0',
  'area': 'luck_pillars',
  'kind': 'profile',
  'source_anchor': 'anchor.timing.luck_pillars',
  'source_reference_status': 'seed_verified_by_existing_test',
  'input': {'datetime_utc': '2000-02-06T12:00:00+00:00', 'timezone': 'UTC'},
  'options': {'calculation_sex': 'male', 'include_luck_pillars': True, 'luck_direction_rule': 'day_stem_polarity'},
  'expected': {'paths': {'timing.direction_rule_key': 'day_stem_polarity', 'timing.polarity_source': 'day_stem'}}},
 {'id': 'luck.hko_2026_forward_jing_zhe_start_age',
  'phase': 'V2',
  'priority': 'P0',
  'area': 'luck_pillars',
  'kind': 'profile',
  'source_anchor': 'anchor.timing.luck_pillars',
  'external_anchor': 'web.hko_24_solar_terms',
  'source_reference_status': 'external_hko_and_local_luck_start_age_seeded',
  'input': {'datetime_utc': '2026-02-04T00:02:00+00:00', 'timezone': 'UTC'},
  'options': {'calculation_sex': 'male', 'include_luck_pillars': True},
  'expected': {'paths': {'timing.direction': 'forward',
                         'timing.debug.solar_term.key': 'jing_zhe',
                         'timing.debug.method': 'three_days_per_year_from_adjacent_jie_solar_term',
                         'timing.start_age_label': '9y 10m',
                         'luck_pillars.0.stem': 'Xin',
                         'luck_pillars.0.branch': 'Mao'},
               'hko_adjacent_term_utc': '2026-03-05T13:59:00+00:00',
               'distance_days': 29.58125,
               'start_age': 9.86,
               'tolerance': {'term_seconds': 90, 'distance_days': 0.01, 'start_age': 0.01}}},
 {'id': 'luck.hko_2026_reverse_li_chun_start_age',
  'phase': 'V2',
  'priority': 'P0',
  'area': 'luck_pillars',
  'kind': 'profile',
  'source_anchor': 'anchor.timing.luck_pillars',
  'external_anchor': 'web.hko_24_solar_terms',
  'source_reference_status': 'external_hko_and_local_luck_start_age_seeded',
  'input': {'datetime_utc': '2026-02-04T00:02:00+00:00', 'timezone': 'UTC'},
  'options': {'calculation_sex': 'female', 'include_luck_pillars': True},
  'expected': {'paths': {'timing.direction': 'reverse',
                         'timing.debug.solar_term.key': 'li_chun',
                         'timing.debug.method': 'three_days_per_year_from_adjacent_jie_solar_term',
                         'timing.start_age_label': '1m',
                         'luck_pillars.0.stem': 'Ji',
                         'luck_pillars.0.branch': 'Chou'},
               'hko_adjacent_term_utc': '2026-02-03T20:02:00+00:00',
               'distance_days': 0.16667,
               'start_age': 0.06,
               'tolerance': {'term_seconds': 90, 'distance_days': 0.01, 'start_age': 0.01}}},
 {'id': 'luck.hko_2026_day_stem_variant_reverses_to_li_chun',
  'phase': 'V2',
  'priority': 'P0',
  'area': 'luck_pillars',
  'kind': 'profile',
  'source_anchor': 'anchor.timing.luck_pillars',
  'external_anchor': 'web.hko_24_solar_terms',
  'source_reference_status': 'external_hko_and_local_luck_variant_seeded',
  'input': {'datetime_utc': '2026-02-04T00:02:00+00:00', 'timezone': 'UTC'},
  'options': {'calculation_sex': 'male', 'include_luck_pillars': True, 'luck_direction_rule': 'day_stem_polarity'},
  'expected': {'paths': {'timing.direction': 'reverse',
                         'timing.direction_rule_key': 'day_stem_polarity',
                         'timing.polarity_source': 'day_stem',
                         'timing.debug.solar_term.key': 'li_chun',
                         'luck_pillars.0.stem': 'Ji',
                         'luck_pillars.0.branch': 'Chou'},
               'hko_adjacent_term_utc': '2026-02-03T20:02:00+00:00',
               'distance_days': 0.16667,
               'start_age': 0.06,
               'tolerance': {'term_seconds': 90, 'distance_days': 0.01, 'start_age': 0.01}}},
 {'id': 'luck.hko_2026_forward_near_jing_zhe_boundary',
  'phase': 'V2',
  'priority': 'P0',
  'area': 'luck_pillars',
  'kind': 'profile',
  'source_anchor': 'anchor.timing.luck_pillars',
  'external_anchor': 'web.hko_24_solar_terms',
  'source_reference_status': 'external_hko_and_local_luck_boundary_seeded',
  'input': {'datetime_utc': '2026-03-05T13:00:00+00:00', 'timezone': 'UTC'},
  'options': {'calculation_sex': 'male', 'include_luck_pillars': True},
 'expected': {'paths': {'timing.direction': 'forward',
                         'timing.debug.solar_term.key': 'jing_zhe',
                         'timing.start_age_label': '0m',
                         'luck_pillars.0.stem': 'Xin',
                         'luck_pillars.0.branch': 'Mao'},
               'hko_adjacent_term_utc': '2026-03-05T13:59:00+00:00',
               'distance_days': 0.04097,
               'start_age': 0.01,
               'tolerance': {'term_seconds': 90, 'distance_days': 0.01, 'start_age': 0.01}}},
 {'id': 'timing_rhythm.current_layers_reference',
  'phase': 'V2',
  'priority': 'P0',
  'area': 'timing_rhythm',
  'kind': 'profile',
  'source_anchor': 'anchor.timing.luck_pillars',
  'external_anchor': 'web.hko_24_solar_terms',
  'source_reference_status': 'local_bazi_timing_and_external_solar_term_seeded',
  'input': {'datetime_utc': '2000-02-06T12:00:00+00:00', 'timezone': 'UTC'},
  'options': {'calculation_sex': 'male', 'include_luck_pillars': True},
  'expected': {'paths': {'timing.rhythm.status': 'source_based_preview',
                         'timing.rhythm.method': 'bazi_timing_rhythm_v1',
                         'timing.rhythm.scope': 'bazi_timing_not_branded_fortune_cycle',
                         'timing.rhythm.layers.0.layer': 'da_yun',
                         'timing.rhythm.layers.1.layer': 'liu_nian',
                         'timing.rhythm.layers.2.layer': 'flowing_month',
                         'timing.rhythm.layers.3.layer': 'flowing_day',
                         'timing.rhythm.layers.4.layer': 'flowing_hour'}}},
 {'id': 'timing_rhythm.growth_stage_day_master_branch',
  'phase': 'V2',
  'priority': 'P1',
  'area': 'timing_rhythm',
  'kind': 'profile',
  'source_anchor': 'anchor.timing.growth_stages',
  'source_reference_status': 'local_growth_stage_table_seeded_needs_more_examples',
  'input': {'datetime_utc': '2000-02-06T12:00:00+00:00', 'timezone': 'UTC'},
  'options': {'calculation_sex': 'male', 'include_luck_pillars': True},
  'expected': {'paths': {'timing.rhythm.layers.0.growth_stage.status': 'source_backed_preview',
                         'timing.rhythm.layers.1.growth_stage.status': 'source_backed_preview'}}},
 {'id': 'timing_rhythm.flowing_month_contact_reference',
  'phase': 'V2',
  'priority': 'P1',
  'area': 'timing_rhythm',
  'kind': 'profile',
  'source_anchor': 'anchor.relationships.codes',
  'source_reference_status': 'local_dynamic_relationship_codes_seeded_preview_only_for_flowing_month',
  'input': {'datetime_utc': '2000-02-06T12:00:00+00:00', 'timezone': 'UTC'},
  'options': {'calculation_sex': 'male', 'include_luck_pillars': True},
  'expected': {'paths': {'relationships.summary.flowing_month': 3,
                         'timing.rhythm.layers.2.layer': 'flowing_month',
                         'timing.rhythm.layers.2.relationship_summary.total': 3,
                         'timing.rhythm.layers.2.source_strength': 'computed_no_worked_example',
                         'timing.rhythm.layers.2.release_gate': 'preview_only_until_worked_examples_curated'}}},
 {'id': 'timing_rhythm.flowing_day_hour_contact_reference',
  'phase': 'V2',
  'priority': 'P1',
  'area': 'timing_rhythm',
  'kind': 'profile',
  'source_anchor': 'anchor.relationships.codes',
  'source_reference_status': 'local_dynamic_relationship_codes_seeded_preview_only_for_flowing_day_hour',
  'input': {'datetime_utc': '2000-02-06T12:00:00+00:00', 'timezone': 'UTC'},
  'options': {'calculation_sex': 'male', 'include_luck_pillars': True},
  'expected': {'paths': {'relationships.summary.flowing_day': 3,
                         'relationships.summary.flowing_hour': 2,
                         'timing.rhythm.layers.3.layer': 'flowing_day',
                         'timing.rhythm.layers.4.layer': 'flowing_hour',
                         'timing.rhythm.layers.3.relationship_summary.total': 3,
                         'timing.rhythm.layers.4.relationship_summary.total': 2,
                         'timing.rhythm.calibration.release_gate': 'timing_assisted_finalization_blocked'}}},
 {'id': 'strength.strong_spring_root',
  'phase': 'V3',
  'priority': 'P1',
  'area': 'strength',
  'kind': 'profile',
  'source_anchor': 'anchor.strength.roots_season',
  'source_reference_status': 'local_strength_page_anchor_seeded',
  'input': {'datetime_utc': '2000-02-06T12:00:00+00:00', 'timezone': 'UTC'},
  'expected': {'paths': {'analysis.strength': 'strong', 'analysis.strength_model.method': 'season_root_formation_v2'}}},
 {'id': 'strength.balanced_withheld_useful',
  'phase': 'V3',
  'priority': 'P1',
  'area': 'useful_elements',
  'kind': 'profile',
  'source_anchor': 'anchor.useful_elements.climate_damage',
  'source_reference_status': 'local_useful_page_anchor_seeded_needs_final_yong_shen_fixtures',
  'input': {'datetime_utc': '2000-01-01T12:00:00+00:00', 'timezone': 'UTC'},
  'expected': {'paths': {'analysis.strength': 'balanced',
                         'useful_elements.status': 'withheld',
                         'useful_elements.useful_god.final_status': 'withheld'}}},
 {'id': 'useful_elements.climate_damage_seed',
  'phase': 'V3',
  'priority': 'P1',
  'area': 'useful_elements',
  'kind': 'function',
  'source_anchor': 'anchor.useful_elements.climate_damage',
  'source_reference_status': 'seed_verified_by_existing_test',
  'expected': {'coverage': 'climate candidates, damaged useful assessment, and Yong Shen withholding'}},
 {'id': 'yong_shen.strong_balancing_family',
  'phase': 'V3',
  'priority': 'P1',
  'area': 'useful_elements',
  'kind': 'rule_family',
  'source_anchor': 'anchor.useful_elements.climate_damage',
  'source_reference_status': 'fixture_placeholder_needs_positive_and_negative_examples',
  'expected': {'decision_path': 'yong_shen.strong_balancing', 'final_status': 'withheld_until_curated'}},
 {'id': 'yong_shen.weak_support_family',
  'phase': 'V3',
  'priority': 'P1',
  'area': 'useful_elements',
  'kind': 'rule_family',
  'source_anchor': 'anchor.useful_elements.climate_damage',
  'source_reference_status': 'fixture_placeholder_needs_positive_and_negative_examples',
  'expected': {'decision_path': 'yong_shen.weak_support', 'final_status': 'withheld_until_curated'}},
 {'id': 'yong_shen.climate_override_family',
  'phase': 'V3',
  'priority': 'P1',
  'area': 'useful_elements',
  'kind': 'rule_family',
  'source_anchor': 'anchor.useful_elements.climate_damage',
  'source_reference_status': 'fixture_placeholder_needs_climate_override_examples',
  'expected': {'decision_path': 'yong_shen.climate_override', 'final_status': 'withheld_until_curated'}},
 {'id': 'yong_shen.damage_withheld_family',
  'phase': 'V3',
  'priority': 'P1',
  'area': 'useful_elements',
  'kind': 'rule_family',
  'source_anchor': 'anchor.useful_elements.climate_damage',
  'source_reference_status': 'fixture_placeholder_needs_damaged_useful_examples',
  'expected': {'decision_path': 'yong_shen.damage_withheld', 'final_status': 'withheld'}},
 {'id': 'yong_shen.special_structure_withheld_family',
  'phase': 'V3',
  'priority': 'P1',
  'area': 'special_structures',
  'kind': 'rule_family',
  'source_anchor': 'anchor.useful_elements.climate_damage',
  'source_reference_status': 'fixture_placeholder_needs_special_structure_examples',
  'expected': {'decision_path': 'yong_shen.special_structure_withheld', 'final_status': 'withheld'}},
 {'id': 'yong_shen.balanced_withheld_family',
  'phase': 'V3',
  'priority': 'P1',
  'area': 'useful_elements',
  'kind': 'rule_family',
  'source_anchor': 'anchor.useful_elements.climate_damage',
  'source_reference_status': 'fixture_placeholder_needs_balanced_chart_examples',
  'expected': {'decision_path': 'yong_shen.balanced_withheld', 'final_status': 'withheld'}},
 {'id': 'relationships.event_type_matrix',
  'phase': 'V4',
  'priority': 'P1',
  'area': 'relationships',
  'kind': 'function',
  'source_anchor': 'anchor.relationships.codes',
  'source_reference_status': 'seed_verified_by_existing_test',
  'expected': {'coverage': 'every configured relationship-code event type appears in at least one fixture'}},
 {'id': 'palaces.relationship_pressure_seed',
  'phase': 'V4',
  'priority': 'P1',
  'area': 'palaces',
  'kind': 'function',
  'source_anchor': 'anchor.relationships.codes',
  'source_reference_status': 'seed_verified_by_existing_test',
  'expected': {'coverage': 'relationship-code events attach to affected Year/Month/Day/Hour palaces'}},
 {'id': 'auxiliary.peach_blossom_pressure_seed',
  'phase': 'V4',
  'priority': 'P1',
  'area': 'auxiliary_stars',
  'kind': 'function',
  'source_anchor': 'anchor.auxiliary.peach_blossom',
  'source_reference_status': 'seed_verified_by_existing_test',
  'expected': {'coverage': 'Peach Blossom target branch, timing activation, and pressure state'}},
 {'id': 'compatibility.romantic_pair_score_seed',
  'phase': 'V4',
  'priority': 'P1',
 'area': 'compatibility',
  'kind': 'pair_profile',
  'source_anchor': 'anchor.relationships.codes',
  'source_reference_status': 'local_source_anchored_calibration_seed',
  'primary_input': {'datetime_utc': '2000-01-01T12:00:00+00:00', 'timezone': 'UTC'},
  'relationship_input': {'datetime_utc': '2000-01-04T12:00:00+00:00', 'timezone': 'UTC'},
  'options': {'calculation_sex': 'female', 'include_luck_pillars': True, 'relationship_context': 'romantic'},
  'expected': {'paths': {'scoring.method': 'bazi_pair_weighted_evidence_score_v1',
                         'scoring.relationship_context': 'romantic',
                         'scoring.calibration.status': 'uncalibrated_product_heuristic',
                         'scoring.grade': 'E',
                         'interpretation.focus': 'high_friction'}}},
 {'id': 'frontend.long_snap_and_missing_coordinate_prompts',
  'phase': 'V5',
  'priority': 'P1',
  'area': 'frontend_workflow',
  'kind': 'component',
  'source_anchor': 'frontend.component_test',
  'source_reference_status': 'component_coverage_seeded',
  'expected': {'coverage': 'long snap labels, true-solar missing longitude prompts, same-snap pair warning'}},
 {'id': 'frontend.reading_history_and_preferences',
  'phase': 'V5',
  'priority': 'P1',
  'area': 'reading_history',
  'kind': 'component',
  'source_anchor': 'frontend.component_test',
  'source_reference_status': 'component_coverage_seeded',
  'expected': {'coverage': 'save, load, clear, and preference reset'}},
 {'id': 'release.focused_command_gate',
  'phase': 'V6',
  'priority': 'P0',
  'area': 'release',
  'kind': 'command_gate',
  'source_anchor': 'docs.electron_updates',
  'source_reference_status': 'defined_not_run_for_this_validation_slice',
  'expected': {'commands': ['python -m pytest backend\\test_chinese_astrology_bazi.py -q',
                            'npm --prefix frontend run test:ui -- astroclockApi.test.mjs chineseAstrologyPage.test.jsx',
                            'npm --prefix frontend run build']}}]

VALIDATION_RELEASE_GATES: List[Dict[str, Any]] = [{'id': 'backend_chinese_astrology_tests',
  'priority': 'P0',
  'command': 'python -m pytest backend\\test_chinese_astrology_bazi.py -q',
  'required_for': 'any Chinese Astrology release candidate'},
 {'id': 'frontend_chinese_astrology_tests',
  'priority': 'P0',
  'command': 'npm --prefix frontend run test:ui -- astroclockApi.test.mjs chineseAstrologyPage.test.jsx',
  'required_for': 'any Chinese Astrology release candidate'},
 {'id': 'frontend_build',
  'priority': 'P0',
  'command': 'npm --prefix frontend run build',
  'required_for': 'desktop packaging candidate'},
 {'id': 'packaged_smoke',
  'priority': 'P0',
  'command': 'package-app-new.bat, then smoke the packaged health/version endpoint',
  'required_for': 'public desktop release'}]

ADVANCED_RULE_FAMILY_FIXTURES: List[Dict[str, Any]] = [
    {
        'id': 'yong_shen.strong_balancing.positive.spring_wealth_clear',
        'phase': 'V3',
        'priority': 'P1',
        'area': 'useful_elements',
        'kind': 'rule_family_fixture',
        'family': 'strong_balancing',
        'polarity': 'positive',
        'source_anchor': 'anchor.useful_elements.climate_damage',
        'source_reference_status': 'local_source_anchored_release_fixture',
        'expected': {
            'decision_path': 'yong_shen.strong_balancing',
            'candidate_role': 'Wealth',
            'final_status': 'final_when_gate_clear',
        },
        'notes': 'Strong Day Master, usable Wealth candidate, no damage or special-structure blocker.',
    },
    {
        'id': 'yong_shen.strong_balancing.positive.output_circulation_clear',
        'phase': 'V3',
        'priority': 'P1',
        'area': 'useful_elements',
        'kind': 'rule_family_fixture',
        'family': 'strong_balancing',
        'polarity': 'positive',
        'source_anchor': 'anchor.useful_elements.climate_damage',
        'source_reference_status': 'local_source_anchored_release_fixture',
        'expected': {
            'decision_path': 'yong_shen.strong_balancing',
            'candidate_role': 'Output',
            'final_status': 'final_when_primary_blocked_and_secondary_curated',
        },
        'notes': 'Strong Day Master with Output retained as a secondary release candidate family.',
    },
    {
        'id': 'yong_shen.strong_balancing.positive.influence_conditional_clear',
        'phase': 'V3',
        'priority': 'P1',
        'area': 'useful_elements',
        'kind': 'rule_family_fixture',
        'family': 'strong_balancing',
        'polarity': 'positive',
        'source_anchor': 'anchor.useful_elements.climate_damage',
        'source_reference_status': 'local_source_anchored_release_fixture',
        'expected': {
            'decision_path': 'yong_shen.strong_balancing',
            'candidate_role': 'Influence',
            'final_status': 'candidate_unless_pressure_is_clear',
        },
        'notes': 'Strong Day Master can use controlling pressure only when it is not already excessive.',
    },
    {
        'id': 'yong_shen.strong_balancing.negative.balanced_chart',
        'phase': 'V3',
        'priority': 'P1',
        'area': 'useful_elements',
        'kind': 'rule_family_fixture',
        'family': 'strong_balancing',
        'polarity': 'negative',
        'source_anchor': 'anchor.useful_elements.climate_damage',
        'source_reference_status': 'local_source_anchored_release_fixture',
        'expected': {'decision_path': 'yong_shen.balanced_withheld', 'final_status': 'withheld'},
        'notes': 'Balanced charts must not use strong-balancing final logic.',
    },
    {
        'id': 'yong_shen.strong_balancing.negative.damaged_primary',
        'phase': 'V3',
        'priority': 'P1',
        'area': 'useful_elements',
        'kind': 'rule_family_fixture',
        'family': 'strong_balancing',
        'polarity': 'negative',
        'source_anchor': 'anchor.useful_elements.climate_damage',
        'source_reference_status': 'local_source_anchored_release_fixture',
        'expected': {'decision_path': 'yong_shen.damage_withheld', 'final_status': 'withheld'},
        'notes': 'A damaged or absent primary candidate blocks ordinary strong-balancing final release.',
    },
    {
        'id': 'yong_shen.strong_balancing.negative.special_structure_flag',
        'phase': 'V3',
        'priority': 'P1',
        'area': 'special_structures',
        'kind': 'rule_family_fixture',
        'family': 'strong_balancing',
        'polarity': 'negative',
        'source_anchor': 'anchor.useful_elements.climate_damage',
        'source_reference_status': 'local_source_anchored_release_fixture',
        'expected': {'decision_path': 'yong_shen.special_structure_withheld', 'final_status': 'withheld'},
        'notes': 'Dominant or extreme structure flags block ordinary final release.',
    },
    {
        'id': 'yong_shen.weak_support.positive.resource_clear',
        'phase': 'V3',
        'priority': 'P1',
        'area': 'useful_elements',
        'kind': 'rule_family_fixture',
        'family': 'weak_support',
        'polarity': 'positive',
        'source_anchor': 'anchor.useful_elements.climate_damage',
        'source_reference_status': 'local_source_anchored_release_fixture',
        'expected': {
            'decision_path': 'yong_shen.weak_support',
            'candidate_role': 'Resource',
            'final_status': 'final_when_gate_clear',
        },
        'notes': 'Weak Day Master can use Resource support when the candidate is present and not damaged.',
    },
    {
        'id': 'yong_shen.weak_support.positive.companion_clear',
        'phase': 'V3',
        'priority': 'P1',
        'area': 'useful_elements',
        'kind': 'rule_family_fixture',
        'family': 'weak_support',
        'polarity': 'positive',
        'source_anchor': 'anchor.useful_elements.climate_damage',
        'source_reference_status': 'local_source_anchored_release_fixture',
        'expected': {
            'decision_path': 'yong_shen.weak_support',
            'candidate_role': 'Companion',
            'final_status': 'candidate_unless_resource_unusable',
        },
        'notes': 'Companion support remains secondary unless Resource is blocked by source-backed conditions.',
    },
    {
        'id': 'yong_shen.weak_support.positive.out_of_season_resource',
        'phase': 'V3',
        'priority': 'P1',
        'area': 'useful_elements',
        'kind': 'rule_family_fixture',
        'family': 'weak_support',
        'polarity': 'positive',
        'source_anchor': 'anchor.useful_elements.climate_damage',
        'source_reference_status': 'local_source_anchored_release_fixture',
        'expected': {
            'decision_path': 'yong_shen.weak_support',
            'candidate_role': 'Resource',
            'final_status': 'final_when_gate_clear',
        },
        'notes': 'Weak out-of-season Day Master favors support before draining or controlling roles.',
    },
    {
        'id': 'yong_shen.weak_support.negative.strong_chart',
        'phase': 'V3',
        'priority': 'P1',
        'area': 'useful_elements',
        'kind': 'rule_family_fixture',
        'family': 'weak_support',
        'polarity': 'negative',
        'source_anchor': 'anchor.useful_elements.climate_damage',
        'source_reference_status': 'local_source_anchored_release_fixture',
        'expected': {'decision_path': 'yong_shen.strong_balancing', 'final_status': 'not_weak_support'},
        'notes': 'Strong charts must not use weak-support final logic.',
    },
    {
        'id': 'yong_shen.weak_support.negative.timing_only_candidate',
        'phase': 'V3',
        'priority': 'P1',
        'area': 'useful_elements',
        'kind': 'rule_family_fixture',
        'family': 'weak_support',
        'polarity': 'negative',
        'source_anchor': 'anchor.useful_elements.climate_damage',
        'source_reference_status': 'local_source_anchored_release_fixture',
        'expected': {'decision_path': 'yong_shen.weak_support', 'final_status': 'withheld'},
        'notes': 'Timing-only support can raise confidence but does not release final Yong Shen by itself.',
    },
    {
        'id': 'yong_shen.weak_support.negative.follow_structure_suspected',
        'phase': 'V3',
        'priority': 'P1',
        'area': 'special_structures',
        'kind': 'rule_family_fixture',
        'family': 'weak_support',
        'polarity': 'negative',
        'source_anchor': 'anchor.useful_elements.climate_damage',
        'source_reference_status': 'local_source_anchored_release_fixture',
        'expected': {'decision_path': 'yong_shen.special_structure_withheld', 'final_status': 'withheld'},
        'notes': 'Possible follow structures block ordinary weak-support final release.',
    },
    {
        'id': 'yong_shen.climate_override.positive.summer_water',
        'phase': 'V3',
        'priority': 'P1',
        'area': 'useful_elements',
        'kind': 'rule_family_fixture',
        'family': 'climate_override',
        'polarity': 'positive',
        'source_anchor': 'anchor.useful_elements.climate_damage',
        'source_reference_status': 'local_source_anchored_decision_path_fixture',
        'expected': {'decision_path': 'yong_shen.climate_override', 'candidate_role': 'regulating'},
        'notes': 'Summer heat can nominate Water as a regulating candidate before ordinary balancing is finalized.',
    },
    {
        'id': 'yong_shen.climate_override.positive.winter_fire',
        'phase': 'V3',
        'priority': 'P1',
        'area': 'useful_elements',
        'kind': 'rule_family_fixture',
        'family': 'climate_override',
        'polarity': 'positive',
        'source_anchor': 'anchor.useful_elements.climate_damage',
        'source_reference_status': 'local_source_anchored_decision_path_fixture',
        'expected': {'decision_path': 'yong_shen.climate_override', 'candidate_role': 'regulating'},
        'notes': 'Winter cold can nominate Fire as a regulating candidate before ordinary balancing is finalized.',
    },
    {
        'id': 'yong_shen.climate_override.positive.autumn_fire',
        'phase': 'V3',
        'priority': 'P1',
        'area': 'useful_elements',
        'kind': 'rule_family_fixture',
        'family': 'climate_override',
        'polarity': 'positive',
        'source_anchor': 'anchor.useful_elements.climate_damage',
        'source_reference_status': 'local_source_anchored_decision_path_fixture',
        'expected': {'decision_path': 'yong_shen.climate_override', 'candidate_role': 'regulating'},
        'notes': 'Autumn cold/dry metal can nominate Fire as a warming/refining regulating candidate.',
    },
    {
        'id': 'yong_shen.climate_override.negative.absent_regulator',
        'phase': 'V3',
        'priority': 'P1',
        'area': 'useful_elements',
        'kind': 'rule_family_fixture',
        'family': 'climate_override',
        'polarity': 'negative',
        'source_anchor': 'anchor.useful_elements.climate_damage',
        'source_reference_status': 'local_source_anchored_decision_path_fixture',
        'expected': {'decision_path': 'yong_shen.climate_override', 'final_status': 'withheld'},
        'notes': 'Climate candidates stay preview when the regulating element is absent or unusable.',
    },
    {
        'id': 'yong_shen.climate_override.negative.special_structure_blocks',
        'phase': 'V3',
        'priority': 'P1',
        'area': 'special_structures',
        'kind': 'rule_family_fixture',
        'family': 'climate_override',
        'polarity': 'negative',
        'source_anchor': 'anchor.useful_elements.climate_damage',
        'source_reference_status': 'local_source_anchored_decision_path_fixture',
        'expected': {'decision_path': 'yong_shen.special_structure_withheld', 'final_status': 'withheld'},
        'notes': 'Climate override cannot finalize while special/follow/transformation review is active.',
    },
    {
        'id': 'yong_shen.climate_override.negative.ordinary_balance_wins',
        'phase': 'V3',
        'priority': 'P1',
        'area': 'useful_elements',
        'kind': 'rule_family_fixture',
        'family': 'climate_override',
        'polarity': 'negative',
        'source_anchor': 'anchor.useful_elements.climate_damage',
        'source_reference_status': 'local_source_anchored_decision_path_fixture',
        'expected': {'decision_path': 'yong_shen.strong_balancing', 'final_status': 'final'},
        'notes': 'Climate row stays evidence-only when the regulating element is not a primary seasonal override.',
    },
]

def _advanced_rule_family_fixture(
    family: str,
    polarity: str,
    slug: str,
    *,
    area: str,
    expected: Dict[str, Any],
    notes: str,
    source_status: str = 'local_source_anchored_release_fixture',
) -> Dict[str, Any]:
    return {
        'id': f'yong_shen.{family}.{polarity}.{slug}',
        'phase': 'V3',
        'priority': 'P1',
        'area': area,
        'kind': 'rule_family_fixture',
        'family': family,
        'polarity': polarity,
        'source_anchor': 'anchor.useful_elements.climate_damage',
        'source_reference_status': source_status,
        'expected': expected,
        'notes': notes,
    }


ADVANCED_RULE_FAMILY_FIXTURES.extend([
    _advanced_rule_family_fixture(
        'dominant_element',
        'positive',
        'fire_dominance_classified',
        area='special_structures',
        expected={'decision_path': 'yong_shen.dominant_element', 'candidate_role': 'dominant', 'final_status': 'final_when_gate_clear'},
        notes='A single non-Day-Master element reaches the classified dominance threshold and no higher-priority structure overrides it.',
    ),
    _advanced_rule_family_fixture(
        'dominant_element',
        'positive',
        'water_dominance_classified',
        area='special_structures',
        expected={'decision_path': 'yong_shen.dominant_element', 'candidate_role': 'dominant', 'final_status': 'final_when_gate_clear'},
        notes='Water dominance is treated as a structural path only after the ratio threshold is classified, not merely suspected.',
    ),
    _advanced_rule_family_fixture(
        'dominant_element',
        'positive',
        'metal_dominance_classified',
        area='special_structures',
        expected={'decision_path': 'yong_shen.dominant_element', 'candidate_role': 'dominant', 'final_status': 'final_when_gate_clear'},
        notes='Metal dominance can graduate when it is the primary classified structure and ordinary balancing is not used.',
    ),
    _advanced_rule_family_fixture(
        'dominant_element',
        'negative',
        'below_ratio_threshold',
        area='special_structures',
        expected={'decision_path': 'yong_shen.special_structure_withheld', 'final_status': 'withheld'},
        notes='Dominance below the classified ratio threshold remains a review flag, not a final structural ruling.',
    ),
    _advanced_rule_family_fixture(
        'dominant_element',
        'negative',
        'transformation_priority_wins',
        area='special_structures',
        expected={'decision_path': 'yong_shen.transformation_structure', 'final_status': 'not_dominant_element'},
        notes='A classified stem transformation outranks a generic dominant-element flag.',
    ),
    _advanced_rule_family_fixture(
        'dominant_element',
        'negative',
        'balanced_distribution',
        area='special_structures',
        expected={'decision_path': 'yong_shen.strong_balancing', 'final_status': 'not_dominant_element'},
        notes='Ordinary charts with no classified dominant structure must keep the standard strength-balancing path.',
    ),
    _advanced_rule_family_fixture(
        'follow_structure',
        'positive',
        'weak_day_follows_fire',
        area='special_structures',
        expected={'decision_path': 'yong_shen.follow_structure', 'candidate_role': 'follow', 'final_status': 'final_when_gate_clear'},
        notes='A weak Day Master with one or fewer Day-element counts can follow a classified dominant element.',
    ),
    _advanced_rule_family_fixture(
        'follow_structure',
        'positive',
        'weak_day_follows_metal',
        area='special_structures',
        expected={'decision_path': 'yong_shen.follow_structure', 'candidate_role': 'follow', 'final_status': 'final_when_gate_clear'},
        notes='Follow structure requires both weak strength evidence and a non-Day-Master dominant element.',
    ),
    _advanced_rule_family_fixture(
        'follow_structure',
        'positive',
        'weak_day_follows_water',
        area='special_structures',
        expected={'decision_path': 'yong_shen.follow_structure', 'candidate_role': 'follow', 'final_status': 'final_when_gate_clear'},
        notes='The follow path is separate from ordinary weak-support logic when the chart is structurally dominated elsewhere.',
    ),
    _advanced_rule_family_fixture(
        'follow_structure',
        'negative',
        'day_element_not_weak',
        area='special_structures',
        expected={'decision_path': 'yong_shen.strong_balancing', 'final_status': 'not_follow_structure'},
        notes='Follow logic must not trigger when the Day Master is not weak.',
    ),
    _advanced_rule_family_fixture(
        'follow_structure',
        'negative',
        'day_element_too_present',
        area='special_structures',
        expected={'decision_path': 'yong_shen.weak_support', 'final_status': 'not_follow_structure'},
        notes='A weak chart with too much Day-element presence remains ordinary weak support rather than follow.',
    ),
    _advanced_rule_family_fixture(
        'follow_structure',
        'negative',
        'dominance_only_suspected',
        area='special_structures',
        expected={'decision_path': 'yong_shen.special_structure_withheld', 'final_status': 'withheld'},
        notes='Suspected follow structures remain withheld until the classified ratio threshold is met.',
    ),
    _advanced_rule_family_fixture(
        'transformation_structure',
        'positive',
        'jia_ji_earth_supported',
        area='special_structures',
        expected={'decision_path': 'yong_shen.transformation_structure', 'candidate_role': 'transformation', 'final_status': 'final_when_gate_clear'},
        notes='Jia-Ji transformation can graduate when Earth is the dominant transformed element.',
    ),
    _advanced_rule_family_fixture(
        'transformation_structure',
        'positive',
        'yi_geng_metal_supported',
        area='special_structures',
        expected={'decision_path': 'yong_shen.transformation_structure', 'candidate_role': 'transformation', 'final_status': 'final_when_gate_clear'},
        notes='Yi-Geng transformation can graduate only when the transformed Metal element is structurally supported.',
    ),
    _advanced_rule_family_fixture(
        'transformation_structure',
        'positive',
        'bing_xin_water_supported',
        area='special_structures',
        expected={'decision_path': 'yong_shen.transformation_structure', 'candidate_role': 'transformation', 'final_status': 'final_when_gate_clear'},
        notes='Bing-Xin transformation uses the transformation family instead of ordinary balancing when Water support is dominant.',
    ),
    _advanced_rule_family_fixture(
        'transformation_structure',
        'negative',
        'pair_without_support',
        area='special_structures',
        expected={'decision_path': 'yong_shen.special_structure_withheld', 'final_status': 'withheld'},
        notes='A stem pair without dominant transformed-element support remains suspected and cannot finalize.',
    ),
    _advanced_rule_family_fixture(
        'transformation_structure',
        'negative',
        'no_stem_pair',
        area='special_structures',
        expected={'decision_path': 'yong_shen.strong_balancing', 'final_status': 'not_transformation_structure'},
        notes='No heavenly-stem transformation pair means the ordinary strength path remains in control.',
    ),
    _advanced_rule_family_fixture(
        'transformation_structure',
        'negative',
        'extreme_strength_review',
        area='special_structures',
        expected={'decision_path': 'yong_shen.special_structure_withheld', 'final_status': 'withheld'},
        notes='Extreme strength labels remain withheld even when a transformation screen is present.',
    ),
    _advanced_rule_family_fixture(
        'damaged_alternate',
        'positive',
        'damaged_primary_output_alternate',
        area='useful_elements',
        expected={'decision_path': 'yong_shen.damaged_alternate', 'candidate_role': 'Output', 'final_status': 'final_when_gate_clear'},
        notes='A damaged primary favorable element can reroute to a present alternate candidate when no special-structure blocker is active.',
    ),
    _advanced_rule_family_fixture(
        'damaged_alternate',
        'positive',
        'absent_primary_influence_alternate',
        area='useful_elements',
        expected={'decision_path': 'yong_shen.damaged_alternate', 'candidate_role': 'Influence', 'final_status': 'final_when_gate_clear'},
        notes='An absent primary candidate can reroute to a clear alternate when the alternate is natal and fixture-backed.',
    ),
    _advanced_rule_family_fixture(
        'damaged_alternate',
        'positive',
        'weak_support_resource_to_companion',
        area='useful_elements',
        expected={'decision_path': 'yong_shen.damaged_alternate', 'candidate_role': 'Companion', 'final_status': 'final_when_gate_clear'},
        notes='Weak-support charts can reroute from damaged Resource to present Companion only when the alternate is usable.',
    ),
    _advanced_rule_family_fixture(
        'damaged_alternate',
        'negative',
        'alternate_also_damaged',
        area='useful_elements',
        expected={'decision_path': 'yong_shen.damage_withheld', 'final_status': 'withheld'},
        notes='No alternate finalization is allowed when the alternate is also damaged.',
    ),
    _advanced_rule_family_fixture(
        'damaged_alternate',
        'negative',
        'alternate_timing_only',
        area='useful_elements',
        expected={'decision_path': 'yong_shen.timing_assisted', 'final_status': 'withheld'},
        notes='Timing-only alternate support remains timing-assisted evidence, not damaged-alternate finalization.',
    ),
    _advanced_rule_family_fixture(
        'damaged_alternate',
        'negative',
        'special_structure_blocks_reroute',
        area='special_structures',
        expected={'decision_path': 'yong_shen.special_structure_withheld', 'final_status': 'withheld'},
        notes='A special-structure flag blocks damaged-candidate rerouting until the structure is classified.',
    ),
    _advanced_rule_family_fixture(
        'tong_guan',
        'positive',
        'fire_bridges_wood_to_earth',
        area='useful_elements',
        expected={'decision_path': 'yong_shen.tong_guan', 'candidate_role': 'Tong Guan', 'final_status': 'final_when_gate_clear'},
        notes='When Wood pressure damages Earth function, Fire can bridge Wood into Earth through the generating cycle.',
    ),
    _advanced_rule_family_fixture(
        'tong_guan',
        'positive',
        'earth_bridges_fire_to_metal',
        area='useful_elements',
        expected={'decision_path': 'yong_shen.tong_guan', 'candidate_role': 'Tong Guan', 'final_status': 'final_when_gate_clear'},
        notes='When Fire pressure damages Metal function, Earth can bridge Fire into Metal through the generating cycle.',
    ),
    _advanced_rule_family_fixture(
        'tong_guan',
        'positive',
        'water_bridges_metal_to_wood',
        area='useful_elements',
        expected={'decision_path': 'yong_shen.tong_guan', 'candidate_role': 'Tong Guan', 'final_status': 'final_when_gate_clear'},
        notes='When Metal pressure damages Wood function, Water can bridge Metal into Wood through the generating cycle.',
    ),
    _advanced_rule_family_fixture(
        'tong_guan',
        'negative',
        'bridge_absent',
        area='useful_elements',
        expected={'decision_path': 'yong_shen.damage_withheld', 'final_status': 'withheld'},
        notes='Tong Guan cannot graduate when the bridge element is absent from natal and timing evidence.',
    ),
    _advanced_rule_family_fixture(
        'tong_guan',
        'negative',
        'ordinary_alternate_clearer',
        area='useful_elements',
        expected={'decision_path': 'yong_shen.damaged_alternate', 'final_status': 'not_tong_guan'},
        notes='A clean ordinary alternate remains preferred over a bridge candidate.',
    ),
    _advanced_rule_family_fixture(
        'tong_guan',
        'negative',
        'special_structure_blocks_bridge',
        area='special_structures',
        expected={'decision_path': 'yong_shen.special_structure_withheld', 'final_status': 'withheld'},
        notes='Special-structure review blocks Tong Guan finalization until the structure path is settled.',
    ),
    _advanced_rule_family_fixture(
        'timing_assisted',
        'positive',
        'decade_supplies_primary',
        area='luck_pillars',
        expected={'decision_path': 'yong_shen.timing_assisted', 'final_status': 'withheld_until_timing_family_released'},
        notes='A decade pillar can supply the candidate and improve evidence, but does not independently finalize Yong Shen.',
        source_status='local_source_anchored_gated_fixture',
    ),
    _advanced_rule_family_fixture(
        'timing_assisted',
        'positive',
        'annual_supports_primary',
        area='luck_pillars',
        expected={'decision_path': 'yong_shen.timing_assisted', 'final_status': 'withheld_until_timing_family_released'},
        notes='Annual support is surfaced as timing evidence while final release remains disabled.',
        source_status='local_source_anchored_gated_fixture',
    ),
    _advanced_rule_family_fixture(
        'timing_assisted',
        'positive',
        'timing_activates_alternate',
        area='luck_pillars',
        expected={'decision_path': 'yong_shen.timing_assisted', 'final_status': 'withheld_until_timing_family_released'},
        notes='Timing can activate an alternate candidate, but timing-only finalization remains gated off.',
        source_status='local_source_anchored_gated_fixture',
    ),
    _advanced_rule_family_fixture(
        'timing_assisted',
        'negative',
        'natal_candidate_available',
        area='luck_pillars',
        expected={'decision_path': 'yong_shen.strong_balancing', 'final_status': 'not_timing_assisted'},
        notes='A natal usable candidate should stay in the ordinary released family rather than timing-assisted.',
        source_status='local_source_anchored_gated_fixture',
    ),
    _advanced_rule_family_fixture(
        'timing_assisted',
        'negative',
        'timing_pressures_candidate',
        area='luck_pillars',
        expected={'decision_path': 'yong_shen.damage_withheld', 'final_status': 'withheld'},
        notes='Timing pressure is not timing-assisted support and must not release final Yong Shen.',
        source_status='local_source_anchored_gated_fixture',
    ),
    _advanced_rule_family_fixture(
        'timing_assisted',
        'negative',
        'no_active_luck_layer',
        area='luck_pillars',
        expected={'decision_path': 'yong_shen.balanced_withheld', 'final_status': 'not_timing_assisted'},
        notes='Timing-assisted logic is inactive without a supplied timing layer.',
        source_status='local_source_anchored_gated_fixture',
    ),
])

VALIDATION_FIXTURES.extend(ADVANCED_RULE_FAMILY_FIXTURES)

COMPATIBILITY_CALIBRATION_FIXTURES: List[Dict[str, Any]] = [
    {
        'id': 'compatibility.general_pair_score_seed',
        'phase': 'V4',
        'priority': 'P1',
        'area': 'compatibility',
        'kind': 'pair_profile',
        'source_anchor': 'anchor.relationships.codes',
        'source_reference_status': 'local_source_anchored_calibration_seed',
        'primary_input': {'datetime_utc': '2000-01-01T12:00:00+00:00', 'timezone': 'UTC'},
        'relationship_input': {'datetime_utc': '2000-01-04T12:00:00+00:00', 'timezone': 'UTC'},
        'options': {'calculation_sex': 'female', 'include_luck_pillars': True, 'relationship_context': 'general'},
        'expected': {
            'paths': {
                'scoring.method': 'bazi_pair_weighted_evidence_score_v1',
                'scoring.relationship_context': 'general',
                'scoring.calibration.status': 'uncalibrated_product_heuristic',
            },
        },
    },
    {
        'id': 'compatibility.family_pair_score_seed',
        'phase': 'V4',
        'priority': 'P1',
        'area': 'compatibility',
        'kind': 'pair_profile',
        'source_anchor': 'anchor.relationships.codes',
        'source_reference_status': 'local_source_anchored_calibration_seed',
        'primary_input': {'datetime_utc': '2000-01-01T12:00:00+00:00', 'timezone': 'UTC'},
        'relationship_input': {'datetime_utc': '2000-01-04T12:00:00+00:00', 'timezone': 'UTC'},
        'options': {'calculation_sex': 'female', 'include_luck_pillars': True, 'relationship_context': 'family'},
        'expected': {
            'paths': {
                'scoring.method': 'bazi_pair_weighted_evidence_score_v1',
                'scoring.relationship_context': 'family',
                'scoring.calibration.status': 'uncalibrated_product_heuristic',
            },
        },
    },
    {
        'id': 'compatibility.business_pair_score_seed',
        'phase': 'V4',
        'priority': 'P1',
        'area': 'compatibility',
        'kind': 'pair_profile',
        'source_anchor': 'anchor.relationships.codes',
        'source_reference_status': 'local_source_anchored_calibration_seed',
        'primary_input': {'datetime_utc': '2000-01-01T12:00:00+00:00', 'timezone': 'UTC'},
        'relationship_input': {'datetime_utc': '2000-01-04T12:00:00+00:00', 'timezone': 'UTC'},
        'options': {'calculation_sex': 'female', 'include_luck_pillars': True, 'relationship_context': 'business'},
        'expected': {
            'paths': {
                'scoring.method': 'bazi_pair_weighted_evidence_score_v1',
                'scoring.relationship_context': 'business',
                'scoring.calibration.status': 'uncalibrated_product_heuristic',
            },
        },
    },
]

VALIDATION_FIXTURES.extend(COMPATIBILITY_CALIBRATION_FIXTURES)

ICHING_ORACLE_FIXTURES: List[Dict[str, Any]] = [
    {
        'id': 'iching.oracle.manual_all_yang_qian',
        'phase': 'V7',
        'priority': 'P1',
        'area': 'iching_oracle',
        'kind': 'oracle_cast',
        'source_anchor': 'local.iching_source_audit_2026_05_11',
        'source_reference_status': 'local_and_public_method_anchored',
        'input': {'method': 'manual', 'lines': [7, 7, 7, 7, 7, 7]},
        'expected': {
            'primary': {'number': 1, 'title': 'The Creative'},
            'changing_lines': [],
            'relating': None,
        },
        'notes': 'Manual line entry is bottom-to-top; six young-yang lines resolve to Qian / The Creative.',
    },
    {
        'id': 'iching.oracle.manual_all_yin_kun',
        'phase': 'V7',
        'priority': 'P1',
        'area': 'iching_oracle',
        'kind': 'oracle_cast',
        'source_anchor': 'local.iching_source_audit_2026_05_11',
        'source_reference_status': 'local_and_public_method_anchored',
        'input': {'method': 'manual', 'lines': [8, 8, 8, 8, 8, 8]},
        'expected': {
            'primary': {'number': 2, 'title': 'The Receptive'},
            'changing_lines': [],
            'relating': None,
        },
        'notes': 'Six young-yin lines resolve to Kun / The Receptive.',
    },
    {
        'id': 'iching.oracle.moving_lines_resulting_hexagram',
        'phase': 'V7',
        'priority': 'P1',
        'area': 'changing_lines',
        'kind': 'oracle_cast',
        'source_anchor': 'public.iching_divination_method',
        'source_reference_status': 'local_and_public_method_anchored',
        'input': {'method': 'manual', 'lines': [6, 7, 8, 9, 7, 8]},
        'expected': {
            'changing_lines': [1, 4],
            'primary': {'number': 60, 'title': 'Limitation'},
            'relating': {'number': 47, 'title': 'Oppression'},
        },
        'notes': 'Old yin changes to yang and old yang changes to yin; the relating hexagram is derived from changed lines.',
    },
    {
        'id': 'iching.oracle.coin_throw_values',
        'phase': 'V7',
        'priority': 'P1',
        'area': 'iching_oracle',
        'kind': 'oracle_cast',
        'source_anchor': 'public.iching_divination_method',
        'source_reference_status': 'local_and_public_method_anchored',
        'input': {
            'method': 'coins',
            'coin_value_scheme': 'heads_2_tails_3',
            'coins': [
                ['heads', 'heads', 'heads'],
                ['heads', 'heads', 'tails'],
                ['heads', 'tails', 'tails'],
                ['tails', 'tails', 'tails'],
                ['heads', 'heads', 'tails'],
                ['heads', 'tails', 'tails'],
            ],
        },
        'expected': {
            'lines': [6, 7, 8, 9, 7, 8],
            'changing_lines': [1, 4],
            'primary': {'number': 60, 'title': 'Limitation'},
            'relating': {'number': 47, 'title': 'Oppression'},
        },
        'notes': 'The default coin scheme follows heads=2 and tails=3 while exposing the school-variant scheme in the API.',
    },
    {
        'id': 'iching.oracle.yarrow_probability_model',
        'phase': 'V7',
        'priority': 'P1',
        'area': 'iching_oracle',
        'kind': 'oracle_cast',
        'source_anchor': 'public.yarrow_stalk_probability_model',
        'source_reference_status': 'local_classic_and_public_method_anchored',
        'input': {'method': 'yarrow', 'seed': 'fixture-yarrow'},
        'expected': {
            'casting_method': 'yarrow_probability',
            'random_model': 'yarrow_stalk_probability_1_5_7_3',
            'line_weights': {'6': 1, '7': 5, '8': 7, '9': 3},
        },
        'notes': 'Yarrow software casting uses the traditional yarrow line probability model instead of equal coin-face probabilities.',
    },
    {
        'id': 'iching.oracle.nuclear_hexagram_structure',
        'phase': 'V7',
        'priority': 'P1',
        'area': 'iching_oracle',
        'kind': 'oracle_structure',
        'source_anchor': 'public.nuclear_hexagram_structure',
        'source_reference_status': 'public_structure_anchored',
        'input': {'method': 'manual', 'lines': [6, 7, 8, 9, 7, 8]},
        'expected': {
            'nuclear': {'number': 50, 'title': 'The Cauldron'},
            'lower_nuclear_lines': [2, 3, 4],
            'upper_nuclear_lines': [3, 4, 5],
        },
        'notes': 'Nuclear hexagram is derived from primary lines 2-4 and 3-5, independent of line movement.',
    },
    {
        'id': 'iching.oracle.zhu_xi_line_policy',
        'phase': 'V7',
        'priority': 'P1',
        'area': 'changing_lines',
        'kind': 'oracle_reading_policy',
        'source_anchor': 'classic.zhu_xi_seven_rule_line_policy',
        'source_reference_status': 'classic_policy_anchored',
        'input': {'method': 'manual', 'lines': [6, 7, 8, 9, 7, 8]},
        'expected': {
            'policy': 'zhu_xi_seven_rule_line_policy',
            'moving_line_count': 2,
            'focus': 'two_moving_lines_upper_primary',
            'primary_line': 4,
        },
        'notes': 'The Oracle exposes Zhu Xi seven-rule focus as a named policy, not as the only possible I Ching school.',
    },
]

VALIDATION_FIXTURES.extend(ICHING_ORACLE_FIXTURES)

YONG_SHEN_RULE_FAMILY_REQUIREMENTS: Dict[str, Dict[str, Any]] = {
    'strong_balancing': {
        'decision_path': 'yong_shen.strong_balancing',
        'min_positive': 3,
        'min_negative': 3,
        'release_enabled': True,
    },
    'weak_support': {
        'decision_path': 'yong_shen.weak_support',
        'min_positive': 3,
        'min_negative': 3,
        'release_enabled': True,
    },
    'climate_override': {
        'decision_path': 'yong_shen.climate_override',
        'min_positive': 3,
        'min_negative': 3,
        'release_enabled': True,
    },
    'dominant_element': {
        'decision_path': 'yong_shen.dominant_element',
        'min_positive': 3,
        'min_negative': 3,
        'release_enabled': True,
    },
    'follow_structure': {
        'decision_path': 'yong_shen.follow_structure',
        'min_positive': 3,
        'min_negative': 3,
        'release_enabled': True,
    },
    'transformation_structure': {
        'decision_path': 'yong_shen.transformation_structure',
        'min_positive': 3,
        'min_negative': 3,
        'release_enabled': True,
    },
    'damaged_alternate': {
        'decision_path': 'yong_shen.damaged_alternate',
        'min_positive': 3,
        'min_negative': 3,
        'release_enabled': True,
    },
    'tong_guan': {
        'decision_path': 'yong_shen.tong_guan',
        'min_positive': 3,
        'min_negative': 3,
        'release_enabled': True,
    },
    'timing_assisted': {
        'decision_path': 'yong_shen.timing_assisted',
        'min_positive': 3,
        'min_negative': 3,
        'release_enabled': False,
    },
    'damage_withheld': {
        'decision_path': 'yong_shen.damage_withheld',
        'min_positive': 0,
        'min_negative': 1,
        'release_enabled': False,
    },
    'special_structure_withheld': {
        'decision_path': 'yong_shen.special_structure_withheld',
        'min_positive': 0,
        'min_negative': 1,
        'release_enabled': False,
    },
    'balanced_withheld': {
        'decision_path': 'yong_shen.balanced_withheld',
        'min_positive': 0,
        'min_negative': 1,
        'release_enabled': False,
    },
}


def _source_status_release_ready(status: str) -> bool:
    text = str(status or '').lower()
    return bool(text) and 'placeholder' not in text and 'needs' not in text


def _executable_rule_family_fixture_ready(fixture: Dict[str, Any]) -> bool:
    chart_input = fixture.get('input')
    assertions = fixture.get('assertions')
    return (
        isinstance(chart_input, dict)
        and bool(chart_input)
        and isinstance(assertions, (dict, list, tuple))
        and bool(assertions)
    )


def advanced_rule_family_status(family: str) -> Dict[str, Any]:
    family_key = str(family or '').replace('yong_shen.', '')
    requirement = dict(YONG_SHEN_RULE_FAMILY_REQUIREMENTS.get(family_key) or {})
    fixtures = [
        fixture for fixture in VALIDATION_FIXTURES
        if fixture.get('kind') == 'rule_family_fixture' and fixture.get('family') == family_key
    ]
    positive = [fixture for fixture in fixtures if fixture.get('polarity') == 'positive']
    negative = [fixture for fixture in fixtures if fixture.get('polarity') == 'negative']
    executable = [fixture for fixture in fixtures if _executable_rule_family_fixture_ready(fixture)]
    executable_positive = [fixture for fixture in executable if fixture.get('polarity') == 'positive']
    executable_negative = [fixture for fixture in executable if fixture.get('polarity') == 'negative']
    non_executable = [
        str(fixture['id']) for fixture in fixtures
        if fixture.get('id') and not _executable_rule_family_fixture_ready(fixture)
    ]
    unanchored = [
        fixture['id'] for fixture in fixtures
        if not _source_status_release_ready(str(fixture.get('source_reference_status') or ''))
    ]
    executable_unanchored = [
        fixture['id'] for fixture in executable
        if not _source_status_release_ready(str(fixture.get('source_reference_status') or ''))
    ]
    min_positive = int(requirement.get('min_positive') or 0)
    min_negative = int(requirement.get('min_negative') or 0)
    has_counts = (
        len(executable_positive) >= min_positive
        and len(executable_negative) >= min_negative
    )
    released = (
        bool(requirement.get('release_enabled'))
        and has_counts
        and not executable_unanchored
    )
    blockers: List[str] = []
    if not requirement:
        blockers.append('family_not_registered')
    if len(positive) < min_positive:
        blockers.append('positive_fixture_gate')
    if len(negative) < min_negative:
        blockers.append('negative_fixture_gate')
    if len(executable_positive) < min_positive:
        blockers.append('executable_positive_fixture_gate')
    if len(executable_negative) < min_negative:
        blockers.append('executable_negative_fixture_gate')
    if executable_unanchored:
        blockers.append('source_anchor_gate')
    if not requirement.get('release_enabled'):
        blockers.append('release_not_enabled')
    return {
        'family': family_key,
        'decision_path': requirement.get('decision_path') or f'yong_shen.{family_key}',
        'released': released,
        'status': 'released' if released else 'blocked',
        'positive_fixture_count': len(positive),
        'negative_fixture_count': len(negative),
        'executable_fixture_qualification': 'chart_input_and_assertions_v1',
        'executable_fixture_count': len(executable),
        'executable_positive_fixture_count': len(executable_positive),
        'executable_negative_fixture_count': len(executable_negative),
        'required_positive': min_positive,
        'required_negative': min_negative,
        'fixture_ids': [str(fixture['id']) for fixture in fixtures if fixture.get('id')],
        'positive_fixture_ids': [str(fixture['id']) for fixture in positive if fixture.get('id')],
        'negative_fixture_ids': [str(fixture['id']) for fixture in negative if fixture.get('id')],
        'executable_fixture_ids': [str(fixture['id']) for fixture in executable if fixture.get('id')],
        'non_executable_fixture_ids': non_executable,
        'unanchored_fixture_ids': unanchored,
        'executable_unanchored_fixture_ids': executable_unanchored,
        'blockers': blockers,
    }


def yong_shen_family_gate(family: str) -> Dict[str, Any]:
    return advanced_rule_family_status(family)


def released_yong_shen_families() -> List[str]:
    return [
        family for family in YONG_SHEN_RULE_FAMILY_REQUIREMENTS
        if advanced_rule_family_status(family).get('released')
    ]


def validation_fixtures_for_phase(phase_id: str) -> List[Dict[str, Any]]:
    return [fixture for fixture in VALIDATION_FIXTURES if fixture.get("phase") == phase_id]


def validation_fixtures_for_area(area: str) -> List[Dict[str, Any]]:
    return [fixture for fixture in VALIDATION_FIXTURES if fixture.get("area") == area]


def validation_summary() -> Dict[str, Any]:
    phases = []
    for phase in VALIDATION_PHASES:
        row = dict(phase)
        row["fixture_count"] = len(validation_fixtures_for_phase(str(phase.get("id") or "")))
        phases.append(row)
    advanced_families = [
        advanced_rule_family_status(family)
        for family in YONG_SHEN_RULE_FAMILY_REQUIREMENTS
    ]
    return {
        "status": "validation_fixture_ledger_seeded",
        "phase_count": len(VALIDATION_PHASES),
        "fixture_count": len(VALIDATION_FIXTURES),
        "p0_fixture_count": sum(1 for fixture in VALIDATION_FIXTURES if fixture.get("priority") == "P0"),
        "areas": sorted({str(fixture.get("area")) for fixture in VALIDATION_FIXTURES if fixture.get("area")}),
        "phases": phases,
        "needs_external_anchor": [
            fixture["id"]
            for fixture in VALIDATION_FIXTURES
            if "needs" in str(fixture.get("source_reference_status") or "")
        ],
        "release_gates": VALIDATION_RELEASE_GATES,
        "advanced_rule_families": advanced_families,
        "released_yong_shen_families": [
            family["family"] for family in advanced_families if family.get("released")
        ],
        "blocked_yong_shen_families": [
            family for family in advanced_families if not family.get("released")
        ],
    }
